In [10]:
pwd

'C:\\Users\\91918\\rna seq'

In [11]:
import os
os.chdir(r"C:\Users\91918")  # Set working directory
print(os.listdir())  # Check available files

['.anaconda', '.conda', '.condarc', '.continuum', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.spyder-py3', '.VirtualBox', '.virtual_documents', '.vscode', 'anaconda3', 'AppData', 'Application Data', 'Barplot_santhosh.png', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'Favorites', 'Human_genome.xlxs.xlsx', 'IntelGraphicsProfiles', 'iris_dataset.txt', 'Jedi', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{64783d22-e0ca-11ef-8b5f-cb0936dff8bb}.TM.blf', 'NTUSER.DAT{64783d22-e0ca-11ef-8b5f-cb0936dff8bb}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{64783d22-e0ca-11ef-8b5f-cb0936dff8bb}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'PrintHood', 'PROGRAMMING', 'R class 1.R', 'R.class- -5.R', 'R.script1.R', 'R.scripts2.R', 'R.scripts3.R', 'Recent', 'resLFC_O_B6J_4w_AL_vs_DR.xlsx', 'resLFC_O_B6J_4w_AL_vs_NR.xlsx', 'resLFC_O_B6J_4w_AL_vs_NRDR.xlsx', 'resLFC_Y_B6J_4w_AL_vs_DR.xlsx', 'resLFC_Y_B6J_4w_AL_vs_NR.xlsx', 'resLFC_Y_B6J_4w_AL_vs_NRDR.xlsx', 'rna seq', 'rtools44', 'R_WORKSHOP.csv', 'SendTo', 'Start Menu', 'Templates', 'Untitled3.ipynb', 'Videos']

In [12]:
pwd

'C:\\Users\\91918'

In [15]:
import pandas as pd
df1 = pd.read_excel("resLFC_Y_B6J_4w_AL_vs_DR.xlsx")

In [16]:
df1

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,gene,log2FoldChange.1
0,Zzz3,924.612989,0.207958,0.126069,0.066322,0.242158,NaN,NaN,NaN,NaN,Zzz3,0.207958
1,Zzef1,1202.105048,0.085021,0.223921,0.560661,0.781190,NaN,NaN,NaN,NaN,Zzef1,0.085021
2,Zyx,847.096494,0.362974,0.328963,0.056781,0.219607,NaN,NaN,NaN,NaN,Zyx,0.362974
3,Zyg11b,2336.250924,0.102107,0.129472,0.378199,0.648529,NaN,NaN,NaN,NaN,Zyg11b,0.102107
4,Zyg11a,58.329681,0.032908,0.212517,0.819979,0.922709,NaN,NaN,NaN,NaN,Zyg11a,0.032908
...,...,...,...,...,...,...,...,...,...,...,...,...
22873,0610010F05Rik,724.076105,-0.078786,0.131940,0.498742,0.740714,NaN,NaN,NaN,NaN,0610010F05Rik,-0.078786
22874,0610009L18Rik,12.334087,-0.229916,0.324790,0.139484,0.378051,NaN,NaN,NaN,NaN,0610009L18Rik,-0.229916
22875,0610009E02Rik,3.800484,-0.002768,0.263786,0.976496,0.991224,NaN,NaN,NaN,NaN,0610009E02Rik,-0.002768
22876,0610009B22Rik,685.437928,-0.843077,0.255959,0.000089,0.001793,NaN,NaN,NaN,NaN,0610009B22Rik,-0.843077
22877,0610005C13Rik,3887.039850,0.378518,0.126990,0.001266,0.014753,NaN,NaN,NaN,NaN,0610005C13Rik,0.378518

In [17]:
df.head

<bound method NDFrame.head of           Unnamed: 0     baseMean  log2FoldChange     lfcSE    pvalue  \
0               Zzz3   924.612989        0.207958  0.126069  0.066322
1              Zzef1  1202.105048        0.085021  0.223921  0.560661
2                Zyx   847.096494        0.362974  0.328963  0.056781
3             Zyg11b  2336.250924        0.102107  0.129472  0.378199
4             Zyg11a    58.329681        0.032908  0.212517  0.819979
...              ...          ...             ...       ...       ...
22873  0610010F05Rik   724.076105       -0.078786  0.131940  0.498742
22874  0610009L18Rik    12.334087       -0.229916  0.324790  0.139484
22875  0610009E02Rik     3.800484       -0.002768  0.263786  0.976496
22876  0610009B22Rik   685.437928       -0.843077  0.255959  0.000089
22877  0610005C13Rik  3887.039850        0.378518  0.126990  0.001266

           padj  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0      0.242158         NaN         NaN         NaN         NaN
1      0.781190         NaN         NaN         NaN         NaN
2      0.219607         NaN         NaN         NaN         NaN
3      0.648529         NaN         NaN         NaN         NaN
4      0.922709         NaN         NaN         NaN         NaN
...         ...         ...         ...         ...         ...
22873  0.740714         NaN         NaN         NaN         NaN
22874  0.378051         NaN         NaN         NaN         NaN
22875  0.991224         NaN         NaN         NaN         NaN
22876  0.001793         NaN         NaN         NaN         NaN
22877  0.014753         NaN         NaN         NaN         NaN

                gene  log2FoldChange.1
0               Zzz3          0.207958
1              Zzef1          0.085021
2                Zyx          0.362974
3             Zyg11b          0.102107
4             Zyg11a          0.032908
...              ...               ...
22873  0610010F05Rik         -0.078786
22874  0610009L18Rik         -0.229916
22875  0610009E02Rik         -0.002768
22876  0610009B22Rik         -0.843077
22877  0610005C13Rik          0.378518

[22878 rows x 12 columns]>

In [18]:
df.head(2)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,gene,log2FoldChange.1
0,Zzz3,924.612989,0.207958,0.126069,0.066322,0.242158,NaN,NaN,NaN,NaN,Zzz3,0.207958
1,Zzef1,1202.105048,0.085021,0.223921,0.560661,0.781190,NaN,NaN,NaN,NaN,Zzef1,0.085021

In [19]:
df.columns

Index(['Unnamed: 0', 'baseMean', 'log2FoldChange', 'lfcSE', 'pvalue', 'padj',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'gene',
       'log2FoldChange.1'],
      dtype='object')

In [20]:
df.tail

<bound method NDFrame.tail of           Unnamed: 0     baseMean  log2FoldChange     lfcSE    pvalue  \
0               Zzz3   924.612989        0.207958  0.126069  0.066322
1              Zzef1  1202.105048        0.085021  0.223921  0.560661
2                Zyx   847.096494        0.362974  0.328963  0.056781
3             Zyg11b  2336.250924        0.102107  0.129472  0.378199
4             Zyg11a    58.329681        0.032908  0.212517  0.819979
...              ...          ...             ...       ...       ...
22873  0610010F05Rik   724.076105       -0.078786  0.131940  0.498742
22874  0610009L18Rik    12.334087       -0.229916  0.324790  0.139484
22875  0610009E02Rik     3.800484       -0.002768  0.263786  0.976496
22876  0610009B22Rik   685.437928       -0.843077  0.255959  0.000089
22877  0610005C13Rik  3887.039850        0.378518  0.126990  0.001266

           padj  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0      0.242158         NaN         NaN         NaN         NaN
1      0.781190         NaN         NaN         NaN         NaN
2      0.219607         NaN         NaN         NaN         NaN
3      0.648529         NaN         NaN         NaN         NaN
4      0.922709         NaN         NaN         NaN         NaN
...         ...         ...         ...         ...         ...
22873  0.740714         NaN         NaN         NaN         NaN
22874  0.378051         NaN         NaN         NaN         NaN
22875  0.991224         NaN         NaN         NaN         NaN
22876  0.001793         NaN         NaN         NaN         NaN
22877  0.014753         NaN         NaN         NaN         NaN

                gene  log2FoldChange.1
0               Zzz3          0.207958
1              Zzef1          0.085021
2                Zyx          0.362974
3             Zyg11b          0.102107
4             Zyg11a          0.032908
...              ...               ...
22873  0610010F05Rik         -0.078786
22874  0610009L18Rik         -0.229916
22875  0610009E02Rik         -0.002768
22876  0610009B22Rik         -0.843077
22877  0610005C13Rik          0.378518

[22878 rows x 12 columns]>

In [22]:
print(df["gene"].tail())

22873    0610010F05Rik
22874    0610009L18Rik
22875    0610009E02Rik
22876    0610009B22Rik
22877    0610005C13Rik
Name: gene, dtype: object

In [21]:
df.shape

(22878, 12)

In [29]:
df.isna

<bound method DataFrame.isna of           Unnamed: 0     baseMean  log2FoldChange     lfcSE    pvalue  \
0               Zzz3   924.612989        0.207958  0.126069  0.066322
1              Zzef1  1202.105048        0.085021  0.223921  0.560661
2                Zyx   847.096494        0.362974  0.328963  0.056781
3             Zyg11b  2336.250924        0.102107  0.129472  0.378199
4             Zyg11a    58.329681        0.032908  0.212517  0.819979
...              ...          ...             ...       ...       ...
22873  0610010F05Rik   724.076105       -0.078786  0.131940  0.498742
22874  0610009L18Rik    12.334087       -0.229916  0.324790  0.139484
22875  0610009E02Rik     3.800484       -0.002768  0.263786  0.976496
22876  0610009B22Rik   685.437928       -0.843077  0.255959  0.000089
22877  0610005C13Rik  3887.039850        0.378518  0.126990  0.001266

           padj  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0      0.242158         NaN         NaN         NaN         NaN
1      0.781190         NaN         NaN         NaN         NaN
2      0.219607         NaN         NaN         NaN         NaN
3      0.648529         NaN         NaN         NaN         NaN
4      0.922709         NaN         NaN         NaN         NaN
...         ...         ...         ...         ...         ...
22873  0.740714         NaN         NaN         NaN         NaN
22874  0.378051         NaN         NaN         NaN         NaN
22875  0.991224         NaN         NaN         NaN         NaN
22876  0.001793         NaN         NaN         NaN         NaN
22877  0.014753         NaN         NaN         NaN         NaN

                gene  log2FoldChange.1
0               Zzz3          0.207958
1              Zzef1          0.085021
2                Zyx          0.362974
3             Zyg11b          0.102107
4             Zyg11a          0.032908
...              ...               ...
22873  0610010F05Rik         -0.078786
22874  0610009L18Rik         -0.229916
22875  0610009E02Rik         -0.002768
22876  0610009B22Rik         -0.843077
22877  0610005C13Rik          0.378518

[22878 rows x 12 columns]>

In [25]:
unique_genes=df["gene"].unique()
print(unique_genes)

['Zzz3' 'Zzef1' 'Zyx' ... '0610009E02Rik' '0610009B22Rik' '0610005C13Rik']

In [28]:
num_unique_genes=df["gene"].nunique()
print(f" number of unique genes: {num_unique_genes}")

 number of unique genes: 22878