In [1]:
pwd

'C:\\Users\\91918\\Downloads'

In [5]:
import pandas as pd

In [11]:
name="santhosh"
print(name)

santhosh

In [16]:
pwd

'C:\\Users\\91918\\Downloads'

In [11]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\91918\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\91918\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd
df = pd.read_excel("resLFC_O_B6J_4w_AL_vs_NR.xlsx")

In [3]:
df

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,-log2FC
0,Xkr4,2.449316,2.895589e-07,0.001443,0.783650,0.999926,NaN,NaN,NaN,-2.895589e-07
1,Sox17,24.891324,-6.944587e-07,0.001443,0.765563,0.999926,NaN,NaN,NaN,6.944587e-07
2,Gm7357,5.078738,-9.419395e-07,0.001443,0.572615,0.999926,NaN,NaN,NaN,9.419395e-07
3,Gm6085,42.499403,2.544385e-06,0.001443,0.537142,0.999926,NaN,NaN,NaN,-2.544385e-06
4,Gm6119,5.569959,-8.486273e-07,0.001443,0.577642,0.999926,NaN,NaN,NaN,8.486273e-07
...,...,...,...,...,...,...,...,...,...,...
23623,AC125149.4,0.582299,-2.696822e-07,0.001443,0.466881,0.999926,NaN,NaN,NaN,2.696822e-07
23624,AC168977.2,11.055031,9.581723e-07,0.001443,0.642268,0.999926,NaN,NaN,NaN,-9.581723e-07
23625,AC168977.1,22.016405,2.363822e-06,0.001443,0.116955,0.999926,NaN,NaN,NaN,-2.363822e-06
23626,AC149090.1,610.601180,-2.409320e-06,0.001443,0.643544,0.999926,NaN,NaN,NaN,2.409320e-06
23627,CAAA01147332.1,408.820909,-4.827505e-06,0.001443,0.374228,0.999926,NaN,NaN,NaN,4.827505e-06

In [14]:
df.head

<bound method NDFrame.head of            Unnamed: 0    baseMean  log2FoldChange     lfcSE    pvalue  \
0                Xkr4    2.449316    2.895589e-07  0.001443  0.783650
1               Sox17   24.891324   -6.944587e-07  0.001443  0.765563
2              Gm7357    5.078738   -9.419395e-07  0.001443  0.572615
3              Gm6085   42.499403    2.544385e-06  0.001443  0.537142
4              Gm6119    5.569959   -8.486273e-07  0.001443  0.577642
...               ...         ...             ...       ...       ...
23623      AC125149.4    0.582299   -2.696822e-07  0.001443  0.466881
23624      AC168977.2   11.055031    9.581723e-07  0.001443  0.642268
23625      AC168977.1   22.016405    2.363822e-06  0.001443  0.116955
23626      AC149090.1  610.601180   -2.409320e-06  0.001443  0.643544
23627  CAAA01147332.1  408.820909   -4.827505e-06  0.001443  0.374228

           padj  Unnamed: 6  Unnamed: 7  Unnamed: 8       -log2FC
0      0.999926         NaN         NaN         NaN -2.895589e-07
1      0.999926         NaN         NaN         NaN  6.944587e-07
2      0.999926         NaN         NaN         NaN  9.419395e-07
3      0.999926         NaN         NaN         NaN -2.544385e-06
4      0.999926         NaN         NaN         NaN  8.486273e-07
...         ...         ...         ...         ...           ...
23623  0.999926         NaN         NaN         NaN  2.696822e-07
23624  0.999926         NaN         NaN         NaN -9.581723e-07
23625  0.999926         NaN         NaN         NaN -2.363822e-06
23626  0.999926         NaN         NaN         NaN  2.409320e-06
23627  0.999926         NaN         NaN         NaN  4.827505e-06

[23628 rows x 10 columns]>

In [4]:
df.head(2)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,-log2FC
0,Xkr4,2.449316,2.895589e-07,0.001443,0.783650,0.999926,NaN,NaN,NaN,-2.895589e-07
1,Sox17,24.891324,-6.944587e-07,0.001443,0.765563,0.999926,NaN,NaN,NaN,6.944587e-07

In [5]:
df.tail(3)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,-log2FC
23625,AC168977.1,22.016405,0.000002,0.001443,0.116955,0.999926,NaN,NaN,NaN,-0.000002
23626,AC149090.1,610.601180,-0.000002,0.001443,0.643544,0.999926,NaN,NaN,NaN,0.000002
23627,CAAA01147332.1,408.820909,-0.000005,0.001443,0.374228,0.999926,NaN,NaN,NaN,0.000005

In [6]:
df.columns

Index(['Unnamed: 0', 'baseMean', 'log2FoldChange', 'lfcSE', 'pvalue', 'padj',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', ' -log2FC'],
      dtype='object')

In [13]:
df.isna

<bound method DataFrame.isna of            Unnamed: 0    baseMean  log2FoldChange     lfcSE    pvalue  \
0                Xkr4    2.449316    2.895589e-07  0.001443  0.783650
1               Sox17   24.891324   -6.944587e-07  0.001443  0.765563
2              Gm7357    5.078738   -9.419395e-07  0.001443  0.572615
3              Gm6085   42.499403    2.544385e-06  0.001443  0.537142
4              Gm6119    5.569959   -8.486273e-07  0.001443  0.577642
...               ...         ...             ...       ...       ...
23623      AC125149.4    0.582299   -2.696822e-07  0.001443  0.466881
23624      AC168977.2   11.055031    9.581723e-07  0.001443  0.642268
23625      AC168977.1   22.016405    2.363822e-06  0.001443  0.116955
23626      AC149090.1  610.601180   -2.409320e-06  0.001443  0.643544
23627  CAAA01147332.1  408.820909   -4.827505e-06  0.001443  0.374228

           padj  Unnamed: 6  Unnamed: 7  Unnamed: 8       -log2FC
0      0.999926         NaN         NaN         NaN -2.895589e-07
1      0.999926         NaN         NaN         NaN  6.944587e-07
2      0.999926         NaN         NaN         NaN  9.419395e-07
3      0.999926         NaN         NaN         NaN -2.544385e-06
4      0.999926         NaN         NaN         NaN  8.486273e-07
...         ...         ...         ...         ...           ...
23623  0.999926         NaN         NaN         NaN  2.696822e-07
23624  0.999926         NaN         NaN         NaN -9.581723e-07
23625  0.999926         NaN         NaN         NaN -2.363822e-06
23626  0.999926         NaN         NaN         NaN  2.409320e-06
23627  0.999926         NaN         NaN         NaN  4.827505e-06

[23628 rows x 10 columns]>

In [33]:
df["gene"].unique()

array(['Xkr4', 'Sox17', 'Gm7357', ..., 'AC168977.1', 'AC149090.1',
       'CAAA01147332.1'], shape=(23628,), dtype=object)

In [34]:
unique_genes = df["gene"].unique()
print(unique_genes)

['Xkr4' 'Sox17' 'Gm7357' ... 'AC168977.1' 'AC149090.1' 'CAAA01147332.1']

In [35]:
num_unique_genes = df["gene"].nunique()
print(f"Number of unique genes: {num_unique_genes}")

Number of unique genes: 23628