In [2]:
pwd

'C:\\Users\\91918\\rna seq'

In [3]:
import os
os.chdir("C://Users//91918")

In [4]:
pwd

'C:\\Users\\91918'

In [5]:
import pandas as pd
df=pd.read_excel("liver proteome.xlsx")

In [6]:
df

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [49]:
df.columns

Index(['Comparison (group1/group2)', 'Group', 'ProteinGroups',
       'AVG Log2 Ratio', 'Absolute AVG Log2 Ratio', 'Pvalue', 'Qvalue',
       '# of Ratios', 'UniProtIds', 'Genes', 'ProteinDescriptions',
       'ProteinNames', '# Unique Total Peptides', '% Change', 'Ratio',
       'Condition Numerator', 'Condition Denominator', 'GO Cellular Component',
       'GO Molecular Function', 'GO Biological Process'],
      dtype='object')

In [20]:
#display(df["Qvalue"])

In [19]:
find_Qvalue_df=df[df["Qvalue"] < 0.05]
#display(find_Qvalue_df)

In [18]:
Qvalue_filtered = df[df["Qvalue"] < 0.05]
#display(Qvalue_filtered)

In [9]:
filtered_df= df[df["Comparison (group1/group2)"] == "O_DR / O_AL"]
display(filtered_df)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
9,O_DR / O_AL,Q8C196,Q8C196,0.452917,0.452917,9.817179e-183,4.058422e-179,4559,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,36.880536,1.368805,O_DR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
18,O_DR / O_AL,P19096,P19096,-0.383790,0.383790,5.379404e-131,1.170445e-127,3020,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.357825,0.766422,O_DR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
25,O_DR / O_AL,Q91Y97,Q91Y97,0.644823,0.644823,2.083733e-113,3.313135e-110,1273,Q91Y97,Aldob,Fructose-bisphosphate aldolase B,ALDOB_MOUSE,38,56.354710,1.563547,O_DR,O_AL,"microtubule organizing center,centriolar satel...","fructose-bisphosphate aldolase activity,cytosk...","fructose metabolic process,glycolytic process,..."
29,O_DR / O_AL,Q99K67,Q99K67,0.948140,0.948140,4.600325e-105,6.339248e-102,1241,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,92.938305,1.929383,O_DR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
47,O_DR / O_AL,Q91V92,Q91V92,-0.712077,0.712077,1.034209e-91,8.907128e-89,1284,Q91V92,Acly,ATP-citrate synthase,ACLY_MOUSE,66,-38.955936,0.610441,O_DR,O_AL,"nucleoplasm,mitochondrion,cytosol,plasma membr...","ATP citrate synthase activity,protein binding,...","acetyl-CoA biosynthetic process,citrate metabo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85201,O_DR / O_AL,Q8BHD7,Q8BHD7,-0.126343,0.126343,9.973805e-01,4.839235e-01,103,Q8BHD7,Ptbp3,Polypyrimidine tract-binding protein 3,PTBP3_MOUSE,8,-8.384904,0.916151,O_DR,O_AL,nucleus,RNA binding,"mRNA processing,RNA splicing,negative regulati..."
85214,O_DR / O_AL,O88543,O88543,-0.238335,0.238335,9.978434e-01,4.840683e-01,95,O88543,Cops3,COP9 signalosome complex subunit 3,CSN3_MOUSE,7,-15.227682,0.847723,O_DR,O_AL,"nucleus,nucleoplasm,cytosol,COP9 signalosome",protein binding,"protein deneddylation,in utero embryonic devel..."
85220,O_DR / O_AL,Q9CQB2,Q9CQB2,0.243283,0.243283,9.979759e-01,4.841098e-01,38,Q9CQB2,Fam195a,Protein FAM195A,F195A_MOUSE,3,18.368346,1.183683,O_DR,O_AL,"nucleus,cytoplasm,cytoplasmic stress granule",protein binding,biological_process
85274,O_DR / O_AL,Q9WTI7,Q9WTI7,0.088705,0.088705,9.994361e-01,4.845157e-01,305,Q9WTI7,Myo1c,Unconventional myosin-Ic,MYO1C_MOUSE,22,6.341527,1.063415,O_DR,O_AL,"nuclear pore,nucleolus,cytoplasm,cytosol,plasm...","microfilament motor activity,actin binding,rec...","protein targeting,protein targeting to membran..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [21]:
#display(filtered_df["Qvalue"])

In [79]:
qvalue_filtered = filtered_df[filtered_df["Qvalue"] < 0.05]
display(qvalue_filtered)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
9,O_DR / O_AL,Q8C196,Q8C196,0.452917,0.452917,9.817179e-183,4.058422e-179,4559,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,36.880536,1.368805,O_DR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
18,O_DR / O_AL,P19096,P19096,-0.383790,0.383790,5.379404e-131,1.170445e-127,3020,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.357825,0.766422,O_DR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
25,O_DR / O_AL,Q91Y97,Q91Y97,0.644823,0.644823,2.083733e-113,3.313135e-110,1273,Q91Y97,Aldob,Fructose-bisphosphate aldolase B,ALDOB_MOUSE,38,56.354710,1.563547,O_DR,O_AL,"microtubule organizing center,centriolar satel...","fructose-bisphosphate aldolase activity,cytosk...","fructose metabolic process,glycolytic process,..."
29,O_DR / O_AL,Q99K67,Q99K67,0.948140,0.948140,4.600325e-105,6.339248e-102,1241,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,92.938305,1.929383,O_DR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
47,O_DR / O_AL,Q91V92,Q91V92,-0.712077,0.712077,1.034209e-91,8.907128e-89,1284,Q91V92,Acly,ATP-citrate synthase,ACLY_MOUSE,66,-38.955936,0.610441,O_DR,O_AL,"nucleoplasm,mitochondrion,cytosol,plasma membr...","ATP citrate synthase activity,protein binding,...","acetyl-CoA biosynthetic process,citrate metabo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31647,O_DR / O_AL,B1AR13,B1AR13,0.328305,0.328305,3.724093e-02,4.864574e-02,81,B1AR13,Cisd3,"CDGSH iron-sulfur domain-containing protein 3,...",CISD3_MOUSE,6,25.553759,1.255538,O_DR,O_AL,mitochondrion,"metal ion binding,2 iron, 2 sulfur cluster bin...",biological_process
31654,O_DR / O_AL,Q922E4,Q922E4,-0.111135,0.111135,3.727052e-02,4.867362e-02,398,Q922E4,Pcyt2,Ethanolamine-phosphate cytidylyltransferase,PCY2_MOUSE,17,-7.414030,0.925860,O_DR,O_AL,NaN,ethanolamine-phosphate cytidylyltransferase ac...,phosphatidylethanolamine biosynthetic process
31729,O_DR / O_AL,Q61035,Q61035,-0.223675,0.223675,3.765205e-02,4.905564e-02,168,Q61035,Hars,"Histidine--tRNA ligase, cytoplasmic",SYHC_MOUSE,15,-14.361872,0.856381,O_DR,O_AL,"cytoplasm,mitochondrion,cytosol","histidine-tRNA ligase activity,ATP binding","histidyl-tRNA aminoacylation,mitochondrial tra..."
31753,O_DR / O_AL,P62918,P62918,-0.112780,0.112780,3.777302e-02,4.917606e-02,370,P62918,Rpl8,60S ribosomal protein L8,RL8_MOUSE,17,-7.519599,0.924804,O_DR,O_AL,"focal adhesion,membrane,cytosolic large riboso...","RNA binding,structural constituent of ribosome...","cytoplasmic translation,cellular response to n..."
31831,O_DR / O_AL,P46425,P46425,0.596243,0.596243,3.825071e-02,4.967593e-02,13,P46425,Gstp2,Glutathione S-transferase P 2,GSTP2_MOUSE,2,51.177408,1.511774,O_DR,O_AL,"extracellular space,intracellular,mitochondrio...","glutathione transferase activity,glutathione p...","glutathione metabolic process,cellular oxidant..."

In [17]:
qvalue_filtered = filtered_df[filtered_df["Qvalue"] < 0.05]
num_qvalues = len(qvalue_filtered)
print(f"Number of Qvalue entries < 0.05: {num_qvalues}")

Number of Qvalue entries < 0.05: 1343

In [57]:
display(qvalue_filtered)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
9,O_DR / O_AL,Q8C196,Q8C196,0.452917,0.452917,9.817179e-183,4.058422e-179,4559,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,36.880536,1.368805,O_DR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
18,O_DR / O_AL,P19096,P19096,-0.383790,0.383790,5.379404e-131,1.170445e-127,3020,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.357825,0.766422,O_DR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
25,O_DR / O_AL,Q91Y97,Q91Y97,0.644823,0.644823,2.083733e-113,3.313135e-110,1273,Q91Y97,Aldob,Fructose-bisphosphate aldolase B,ALDOB_MOUSE,38,56.354710,1.563547,O_DR,O_AL,"microtubule organizing center,centriolar satel...","fructose-bisphosphate aldolase activity,cytosk...","fructose metabolic process,glycolytic process,..."
29,O_DR / O_AL,Q99K67,Q99K67,0.948140,0.948140,4.600325e-105,6.339248e-102,1241,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,92.938305,1.929383,O_DR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
47,O_DR / O_AL,Q91V92,Q91V92,-0.712077,0.712077,1.034209e-91,8.907128e-89,1284,Q91V92,Acly,ATP-citrate synthase,ACLY_MOUSE,66,-38.955936,0.610441,O_DR,O_AL,"nucleoplasm,mitochondrion,cytosol,plasma membr...","ATP citrate synthase activity,protein binding,...","acetyl-CoA biosynthetic process,citrate metabo..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31647,O_DR / O_AL,B1AR13,B1AR13,0.328305,0.328305,3.724093e-02,4.864574e-02,81,B1AR13,Cisd3,"CDGSH iron-sulfur domain-containing protein 3,...",CISD3_MOUSE,6,25.553759,1.255538,O_DR,O_AL,mitochondrion,"metal ion binding,2 iron, 2 sulfur cluster bin...",biological_process
31654,O_DR / O_AL,Q922E4,Q922E4,-0.111135,0.111135,3.727052e-02,4.867362e-02,398,Q922E4,Pcyt2,Ethanolamine-phosphate cytidylyltransferase,PCY2_MOUSE,17,-7.414030,0.925860,O_DR,O_AL,NaN,ethanolamine-phosphate cytidylyltransferase ac...,phosphatidylethanolamine biosynthetic process
31729,O_DR / O_AL,Q61035,Q61035,-0.223675,0.223675,3.765205e-02,4.905564e-02,168,Q61035,Hars,"Histidine--tRNA ligase, cytoplasmic",SYHC_MOUSE,15,-14.361872,0.856381,O_DR,O_AL,"cytoplasm,mitochondrion,cytosol","histidine-tRNA ligase activity,ATP binding","histidyl-tRNA aminoacylation,mitochondrial tra..."
31753,O_DR / O_AL,P62918,P62918,-0.112780,0.112780,3.777302e-02,4.917606e-02,370,P62918,Rpl8,60S ribosomal protein L8,RL8_MOUSE,17,-7.519599,0.924804,O_DR,O_AL,"focal adhesion,membrane,cytosolic large riboso...","RNA binding,structural constituent of ribosome...","cytoplasmic translation,cellular response to n..."
31831,O_DR / O_AL,P46425,P46425,0.596243,0.596243,3.825071e-02,4.967593e-02,13,P46425,Gstp2,Glutathione S-transferase P 2,GSTP2_MOUSE,2,51.177408,1.511774,O_DR,O_AL,"extracellular space,intracellular,mitochondrio...","glutathione transferase activity,glutathione p...","glutathione metabolic process,cellular oxidant..."

In [58]:
#number of genes which are differentially expressed (<0.05) in O_DR / O_AL are =1343

In [15]:
# Extract only gene names
differentially_expressed_genes = filtered_df["Genes"].tolist()

# Display first 10 genes
print(differentially_expressed_genes[:10])

['Cps1', 'Fasn', 'Aldob', 'Aass', 'Acly', 'Pc', 'Myh9', 'Sardh', 'Tf', 'Aco2']

In [28]:
filtered_df[["Genes",]].to_csv("O_DR_O_AL_DEGs.csv", index=False)

In [59]:
pwd

'C:\\Users\\91918'

In [60]:
import os 
os.chdir("C://Users//91918")

In [61]:
import pandas as pd
df1=pd.read_excel("liver proteome.xlsx")

In [62]:
df1

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [63]:
filtered_df1=df1[df1["Comparison (group1/group2)"] == "O_NR / O_AL"]
display(filtered_df1) # display will give a clear table of the observing data

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
3678,O_NR / O_AL,Q99PL5,Q99PL5,-0.123758,0.123758,3.434753e-13,3.859546e-12,1612,Q99PL5,Rrbp1,Ribosome-binding protein 1,RRBP1_MOUSE,85,-8.220595,0.917794,O_NR,O_AL,"ribosome,integral component of endoplasmic ret...","receptor activity,protein binding","translation,signal transduction,protein transport"
3833,O_NR / O_AL,P97501,P97501,-0.373383,0.373383,7.524971e-13,8.113779e-12,530,P97501,Fmo3,Dimethylaniline monooxygenase [N-oxide-forming] 3,FMO3_MOUSE,26,-22.803003,0.771970,O_NR,O_AL,"endoplasmic reticulum membrane,integral compon...","monooxygenase activity,N,N-dimethylaniline mon...",oxidation-reduction process
3919,O_NR / O_AL,P43883,P43883,0.524577,0.524577,1.167484e-12,1.231219e-11,286,P43883,Plin2,Perilipin-2,PLIN2_MOUSE,17,43.851128,1.438511,O_NR,O_AL,"nucleus,cytoplasm,lipid particle,cytosol,plasm...",protein binding,"response to organic cyclic compound,long-chain..."
4995,O_NR / O_AL,P25688,P25688,-0.308591,0.308591,1.291291e-10,1.068494e-09,886,P25688,Uox,Uricase,URIC_MOUSE,30,-19.257009,0.807430,O_NR,O_AL,"mitochondrion,peroxisome",urate oxidase activity,"purine nucleobase metabolic process,urate cata..."
5092,O_NR / O_AL,Q8CC88,Q8CC88,0.152147,0.152147,1.842818e-10,1.495820e-09,1010,Q8CC88,Vwa8,von Willebrand factor A domain-containing prot...,VWA8_MOUSE,72,11.122172,1.111222,O_NR,O_AL,"extracellular region,mitochondrion","molecular_function,ATP binding,ATPase activity",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85130,O_NR / O_AL,Q8C0D5,Q8C0D5,-0.093973,0.093973,9.956963e-01,4.835146e-01,83,Q8C0D5,Eftud1,Elongation factor Tu GTP-binding domain-contai...,ETUD1_MOUSE,8,-6.306077,0.936939,O_NR,O_AL,NaN,"translation elongation factor activity,GTPase ...","translational elongation,mature ribosome assem..."
85135,O_NR / O_AL,O08573,O08573,-0.080574,0.080574,9.958675e-01,4.835625e-01,203,O08573,Lgals9,Galectin-9,LEG9_MOUSE,13,-5.431855,0.945681,O_NR,O_AL,"extracellular region,intracellular,nucleus,cyt...","receptor binding,protein binding,galactoside b...","positive regulation of cytokine production,imm..."
85140,O_NR / O_AL,Q61112,Q61112,0.041969,0.041969,9.959198e-01,4.835664e-01,24,Q61112,Sdf4,45 kDa calcium-binding protein,CAB45_MOUSE,2,2.951821,1.029518,O_NR,O_AL,"late endosome,Golgi apparatus,Golgi lumen,memb...",calcium ion binding,"UV protection,cerebellum development,fat cell ..."
85183,O_NR / O_AL,Q6P542,Q6P542,0.231689,0.231689,9.969824e-01,4.838266e-01,180,Q6P542,Abcf1,ATP-binding cassette sub-family F member 1,ABCF1_MOUSE,15,17.420850,1.174208,O_NR,O_AL,"nuclear envelope,nucleoplasm,cytoplasm,cytosol...","RNA binding,ATP binding,translation activator ...","translational initiation,positive regulation o..."
85216,O_NR / O_AL,Q8R1Q9,Q8R1Q9,0.073797,0.073797,9.978415e-01,4.840683e-01,48,Q8R1Q9,Rbks,Ribokinase,RBSK_MOUSE,4,5.248339,1.052483,O_NR,O_AL,"nucleus,cytoplasm,extracellular exosome","ribokinase activity,ATP binding,carbohydrate k...","D-ribose catabolic process,carbohydrate phosph..."

In [64]:
display(filtered_df1["Qvalue"])

3678     3.859546e-12
3833     8.113779e-12
3919     1.231219e-11
4995     1.068494e-09
5092     1.495820e-09
             ...
85130    4.835146e-01
85135    4.835625e-01
85140    4.835664e-01
85183    4.838266e-01
85216    4.840683e-01
Name: Qvalue, Length: 3052, dtype: float64

In [65]:
display(filtered_df1["Qvalue"] < 0.05)

3678      True
3833      True
3919      True
4995      True
5092      True
         ...
85130    False
85135    False
85140    False
85183    False
85216    False
Name: Qvalue, Length: 3052, dtype: bool

In [66]:
filtered_qvalue=filtered_df1[filtered_df1["Qvalue"] < 0.05]
display(filtered_qvalue)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
3678,O_NR / O_AL,Q99PL5,Q99PL5,-0.123758,0.123758,3.434753e-13,3.859546e-12,1612,Q99PL5,Rrbp1,Ribosome-binding protein 1,RRBP1_MOUSE,85,-8.220595,0.917794,O_NR,O_AL,"ribosome,integral component of endoplasmic ret...","receptor activity,protein binding","translation,signal transduction,protein transport"
3833,O_NR / O_AL,P97501,P97501,-0.373383,0.373383,7.524971e-13,8.113779e-12,530,P97501,Fmo3,Dimethylaniline monooxygenase [N-oxide-forming] 3,FMO3_MOUSE,26,-22.803003,0.771970,O_NR,O_AL,"endoplasmic reticulum membrane,integral compon...","monooxygenase activity,N,N-dimethylaniline mon...",oxidation-reduction process
3919,O_NR / O_AL,P43883,P43883,0.524577,0.524577,1.167484e-12,1.231219e-11,286,P43883,Plin2,Perilipin-2,PLIN2_MOUSE,17,43.851128,1.438511,O_NR,O_AL,"nucleus,cytoplasm,lipid particle,cytosol,plasm...",protein binding,"response to organic cyclic compound,long-chain..."
4995,O_NR / O_AL,P25688,P25688,-0.308591,0.308591,1.291291e-10,1.068494e-09,886,P25688,Uox,Uricase,URIC_MOUSE,30,-19.257009,0.807430,O_NR,O_AL,"mitochondrion,peroxisome",urate oxidase activity,"purine nucleobase metabolic process,urate cata..."
5092,O_NR / O_AL,Q8CC88,Q8CC88,0.152147,0.152147,1.842818e-10,1.495820e-09,1010,Q8CC88,Vwa8,von Willebrand factor A domain-containing prot...,VWA8_MOUSE,72,11.122172,1.111222,O_NR,O_AL,"extracellular region,mitochondrion","molecular_function,ATP binding,ATPase activity",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31799,O_NR / O_AL,Q99J56,Q99J56,0.012121,0.012121,3.808095e-02,4.950656e-02,60,Q99J56,Derl1,Derlin-1,DERL1_MOUSE,4,0.843713,1.008437,O_NR,O_AL,"early endosome,late endosome,endoplasmic retic...","protease binding,serine-type endopeptidase act...","response to unfolded protein,ER-associated ubi..."
31811,O_NR / O_AL,Q9CWL8,Q9CWL8,0.310333,0.310333,3.816352e-02,4.959515e-02,40,Q9CWL8,Ctnnbl1,Beta-catenin-like protein 1,CTBL1_MOUSE,4,23.999360,1.239994,O_NR,O_AL,"Prp19 complex,nucleus,nucleoplasm,spliceosomal...","protein binding,enzyme binding","apoptotic process,somatic diversification of i..."
31816,O_NR / O_AL,Q9CQZ0,Q9CQZ0,0.248691,0.248691,3.819168e-02,4.962265e-02,12,Q9CQZ0,Ormdl2,ORM1-like protein 2,ORML2_MOUSE,3,18.812842,1.188128,O_NR,O_AL,"endoplasmic reticulum,integral component of me...",molecular_function,"ceramide metabolic process,cellular sphingolip..."
31830,O_NR / O_AL,P50171,P50171,-0.018059,0.018059,3.824867e-02,4.967485e-02,168,P50171,Hsd17b8,Estradiol 17-beta-dehydrogenase 8,DHB8_MOUSE,10,-1.243959,0.987560,O_NR,O_AL,"mitochondrion,mitochondrial envelope,mitochond...","3-hydroxyacyl-CoA dehydrogenase activity,estra...","fatty acid biosynthetic process,estrogen biosy..."
31869,O_NR / O_AL,P70362,P70362,0.166774,0.166774,3.850167e-02,4.994199e-02,82,P70362,Ufd1l,Ubiquitin fusion degradation protein 1 homolog,UFD1_MOUSE,7,12.254559,1.122546,O_NR,O_AL,"nucleus,cytoplasm,endoplasmic reticulum,cytoso...","receptor binding,protein binding,protein compl...","ubiquitin-dependent protein catabolic process,..."

In [67]:
qvalue_filtered = filtered_df1[filtered_df1["Qvalue"] < 0.05]
num_qvalues = len(qvalue_filtered)
print(f"Number of Qvalue entries < 0.05: {num_qvalues}")

Number of Qvalue entries < 0.05: 424

In [68]:
# differentially expressed genes in (O_AL / O_NR) are = 424

In [69]:
pwd

'C:\\Users\\91918'

In [70]:
df2=df1

In [71]:
df2

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [72]:
filtered_df2=df2[df2["Comparison (group1/group2)"] == "O_NRDR / O_AL"]
display(filtered_df2)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
5,O_NRDR / O_AL,Q8C196,Q8C196,0.510709,0.510709,1.438915e-260,9.914122e-257,4539,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,42.474992,1.424750,O_NRDR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
12,O_NRDR / O_AL,P19096,P19096,-0.392575,0.392575,2.041633e-154,6.492391e-151,3046,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.823113,0.761769,O_NRDR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
30,O_NRDR / O_AL,Q99K67,Q99K67,0.903527,0.903527,3.768567e-103,5.025566e-100,1225,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,87.063407,1.870634,O_NRDR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
38,O_NRDR / O_AL,Q9DBM2,Q9DBM2,0.523532,0.523532,1.727593e-95,1.831249e-92,1443,Q9DBM2,Ehhadh,Peroxisomal bifunctional enzyme,ECHP_MOUSE,59,43.747039,1.437470,O_NRDR,O_AL,"mitochondrion,peroxisome,cytosol","3-hydroxyacyl-CoA dehydrogenase activity,dodec...","internal protein amino acid acetylation,fatty ..."
40,O_NRDR / O_AL,Q99LB7,Q99LB7,0.383591,0.383591,5.251194e-95,5.294740e-92,1604,Q99LB7,Sardh,"Sarcosine dehydrogenase, mitochondrial",SARDH_MOUSE,62,30.458516,1.304585,O_NRDR,O_AL,"mitochondrion,mitochondrial matrix",sarcosine dehydrogenase activity,"oxidation-reduction process,sarcosine cataboli..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85084,O_NRDR / O_AL,P61965,P61965,-0.017083,0.017083,9.944823e-01,4.831542e-01,26,P61965,Wdr5,WD repeat-containing protein 5,WDR5_MOUSE,2,-1.177137,0.988229,O_NRDR,O_AL,"histone acetyltransferase complex,intracellula...","protein binding,methylated histone binding,his...","skeletal system development,transcription, DNA..."
85150,O_NRDR / O_AL,Q921F2,Q921F2,-0.104056,0.104056,9.960645e-01,4.835841e-01,164,Q921F2,Tardbp,TAR DNA-binding protein 43,TADBP_MOUSE,8,-6.958670,0.930413,O_NRDR,O_AL,"nucleus,nucleoplasm,perichromatin fibrils,cyto...","transcriptional activator activity, RNA polyme...",negative regulation of protein phosphorylation...
85238,O_NRDR / O_AL,P56528,P56528,-0.058562,0.058562,9.984121e-01,4.842191e-01,25,P56528,Cd38,ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase 1,CD38_MOUSE,2,-3.977944,0.960221,O_NRDR,O_AL,"nucleus,plasma membrane,cell surface,membrane,...","NAD+ nucleosidase activity,transferase activit...","response to hypoxia,positive regulation of cyt..."
85258,O_NRDR / O_AL,Q99L27,Q99L27,-0.461384,0.461384,9.989909e-01,4.843862e-01,27,Q99L27,Gmpr2,GMP reductase 2,GMPR2_MOUSE,4,-27.371067,0.726289,O_NRDR,O_AL,GMP reductase complex,"GMP reductase activity,metal ion binding","purine nucleobase metabolic process,monocyte d..."
85288,O_NRDR / O_AL,Q9R0A0,Q9R0A0,0.195764,0.195764,9.997834e-01,4.846000e-01,102,Q9R0A0,Pex14,Peroxisomal membrane protein PEX14,PEX14_MOUSE,8,14.533067,1.145331,O_NRDR,O_AL,"fibrillar center,intracellular,peroxisome,pero...","transcription corepressor activity,receptor bi...","protein complex assembly,protein import into p..."

In [73]:
display(filtered_df2["Qvalue"])

5        9.914122e-257
12       6.492391e-151
30       5.025566e-100
38        1.831249e-92
40        5.294740e-92
             ...
85084     4.831542e-01
85150     4.835841e-01
85238     4.842191e-01
85258     4.843862e-01
85288     4.846000e-01
Name: Qvalue, Length: 3049, dtype: float64

In [74]:
filtered_qvalue=filtered_df2[filtered_df2["Qvalue"] < 0.05]
display(filtered_qvalue)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
5,O_NRDR / O_AL,Q8C196,Q8C196,0.510709,0.510709,1.438915e-260,9.914122e-257,4539,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,42.474992,1.424750,O_NRDR,O_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
12,O_NRDR / O_AL,P19096,P19096,-0.392575,0.392575,2.041633e-154,6.492391e-151,3046,P19096,Fasn,Fatty acid synthase,FAS_MOUSE,123,-23.823113,0.761769,O_NRDR,O_AL,"mitochondrion,Golgi apparatus,cytosol,plasma m...","RNA binding,fatty acid synthase activity,[acyl...","osteoblast differentiation,acetyl-CoA metaboli..."
30,O_NRDR / O_AL,Q99K67,Q99K67,0.903527,0.903527,3.768567e-103,5.025566e-100,1225,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,87.063407,1.870634,O_NRDR,O_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
38,O_NRDR / O_AL,Q9DBM2,Q9DBM2,0.523532,0.523532,1.727593e-95,1.831249e-92,1443,Q9DBM2,Ehhadh,Peroxisomal bifunctional enzyme,ECHP_MOUSE,59,43.747039,1.437470,O_NRDR,O_AL,"mitochondrion,peroxisome,cytosol","3-hydroxyacyl-CoA dehydrogenase activity,dodec...","internal protein amino acid acetylation,fatty ..."
40,O_NRDR / O_AL,Q99LB7,Q99LB7,0.383591,0.383591,5.251194e-95,5.294740e-92,1604,Q99LB7,Sardh,"Sarcosine dehydrogenase, mitochondrial",SARDH_MOUSE,62,30.458516,1.304585,O_NRDR,O_AL,"mitochondrion,mitochondrial matrix",sarcosine dehydrogenase activity,"oxidation-reduction process,sarcosine cataboli..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31646,O_NRDR / O_AL,O55042,O55042,0.232723,0.232723,3.723901e-02,4.864476e-02,33,O55042,Snca,Alpha-synuclein,SYUA_MOUSE,3,17.505035,1.175050,O_NRDR,O_AL,"extracellular region,extracellular space,nucle...","magnesium ion binding,copper ion binding,calci...","microglial cell activation,positive regulation..."
31660,O_NRDR / O_AL,Q60605,Q60605,-0.326463,0.326463,3.731773e-02,4.872604e-02,129,Q60605,Myl6,Myosin light polypeptide 6,MYL6_MOUSE,7,-20.251095,0.797489,O_NRDR,O_AL,"brush border,membrane,myosin complex,unconvent...","motor activity,calcium ion binding,protein bin...","muscle contraction,skeletal muscle tissue deve..."
31721,O_NRDR / O_AL,P63276,P63276,-0.093146,0.093146,3.761645e-02,4.902163e-02,220,P63276,Rps17,40S ribosomal protein S17,RS17_MOUSE,11,-6.252389,0.937476,O_NRDR,O_AL,"focal adhesion,membrane,cytosolic small riboso...","RNA binding,structural constituent of ribosome","ribosomal small subunit assembly,rRNA processi..."
31804,O_NRDR / O_AL,Q569Z6,Q569Z6,-0.304713,0.304713,3.812457e-02,4.955521e-02,217,Q569Z6,Thrap3,Thyroid hormone receptor-associated protein 3,TR150_MOUSE,15,-19.039677,0.809603,O_NRDR,O_AL,"nucleus,nucleoplasm,mediator complex,nuclear s...","core promoter sequence-specific DNA binding,RN...","regulation of alternative mRNA splicing, via s..."
31852,O_NRDR / O_AL,O88487,O88487,-0.066315,0.066315,3.836294e-02,4.978728e-02,116,O88487,Dync1i2,Cytoplasmic dynein 1 intermediate chain 2,DC1I2_MOUSE,8,-4.492554,0.955074,O_NRDR,O_AL,"cytoplasm,cytoplasmic dynein complex,microtubu...","protein binding,dynein light chain binding,dyn...","transport along microtubule,positive regulatio..."

In [75]:
num_qvalues=len(filtered_qvalue)
print(f"number of qvalues < 0.05: {num_qvalues}")

number of qvalues < 0.05: 1367

In [ ]:
# differrentially expressed genes in O_AL / O_NRDR are =1367

In [82]:
pwd

'C:\\Users\\91918'

In [83]:
df3=df2

In [84]:
df3

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [87]:
filtered_df3=df3[df3["Comparison (group1/group2)"] == "Y_DR / Y_AL"]
display(filtered_df3)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
41,Y_DR / Y_AL,Q8C196,Q8C196,0.237687,0.237687,5.657942e-95,5.569031e-92,3487,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,17.910064,1.179101,Y_DR,Y_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
229,Y_DR / Y_AL,Q99LB7,Q99LB7,0.271470,0.271470,5.345231e-52,9.607472e-50,1239,Q99LB7,Sardh,"Sarcosine dehydrogenase, mitochondrial",SARDH_MOUSE,62,20.703687,1.207037,Y_DR,Y_AL,"mitochondrion,mitochondrial matrix",sarcosine dehydrogenase activity,"oxidation-reduction process,sarcosine cataboli..."
328,Y_DR / Y_AL,Q99K67,Q99K67,0.625419,0.625419,8.714945e-47,1.095063e-44,952,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,54.265912,1.542659,Y_DR,Y_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
429,Y_DR / Y_AL,P40936,P40936,-0.526075,0.526075,4.549314e-42,4.373689e-40,366,P40936,Inmt,Indolethylamine N-methyltransferase,INMT_MOUSE,18,-30.555852,0.694441,Y_DR,Y_AL,cytosol,"thioether S-methyltransferase activity,amine N...","selenium compound metabolic process,amine meta..."
478,Y_DR / Y_AL,Q571F8,Q571F8,0.503011,0.503011,3.391832e-40,2.927314e-38,452,Q571F8,Gls2,"Glutaminase liver isoform, mitochondrial",GLSL_MOUSE,28,41.716792,1.417168,Y_DR,Y_AL,"mitochondrion,mitochondrial matrix",glutaminase activity,"glutamate biosynthetic process,glutamine catab..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85154,Y_DR / Y_AL,P15532,P15532,-0.392744,0.392744,9.961792e-01,4.836071e-01,88,P15532,Nme1,Nucleoside diphosphate kinase A,NDKA_MOUSE,5,-23.832044,0.761680,Y_DR,Y_AL,"nucleus,mitochondrion,cytosol,membrane,ruffle ...","magnesium ion binding,RNA binding,deoxyribonuc...","nucleoside diphosphate phosphorylation,GTP bio..."
85229,Y_DR / Y_AL,Q80UP8,Q80UP8,-0.318158,0.318158,9.982228e-01,4.841624e-01,30,Q80UP8,Slc20a2,Sodium-dependent phosphate transporter 2,S20A2_MOUSE,3,-19.790689,0.802093,Y_DR,Y_AL,"integral component of plasma membrane,extracel...",inorganic phosphate transmembrane transporter ...,"viral process,phosphate ion transmembrane tran..."
85256,Y_DR / Y_AL,Q9CQF3,Q9CQF3,0.416619,0.416619,9.989165e-01,4.843636e-01,61,Q9CQF3,Nudt21,Cleavage and polyadenylation specificity facto...,CPSF5_MOUSE,5,33.479555,1.334796,Y_DR,Y_AL,"nucleus,centrosome,microtubule organizing cent...","RNA binding,mRNA binding,hydrolase activity,AU...","mRNA polyadenylation,mRNA cleavage,mRNA proces..."
85280,Y_DR / Y_AL,O88738,O88738,-0.281120,0.281120,9.997070e-01,4.845820e-01,88,O88738,Birc6,Baculoviral IAP repeat-containing protein 6,BIRC6_MOUSE,9,-17.704817,0.822952,Y_DR,Y_AL,"spindle pole,cytoplasm,endosome,Golgi apparatu...","ubiquitin-protein transferase activity,cystein...","placenta development,apoptotic process,cell cy..."
85289,Y_DR / Y_AL,P32883,P32883,0.000107,0.000107,9.998263e-01,4.846151e-01,10,P32883,Kras,GTPase KRas,RASK_MOUSE,4,0.007412,1.000074,Y_DR,Y_AL,"cytoplasm,mitochondrion,plasma membrane,focal ...","GTPase activity,protein binding,GTP binding,GM...","liver development,positive regulation of prote..."

In [88]:
display(filtered_df3["Qvalue"])

41       5.569031e-92
229      9.607472e-50
328      1.095063e-44
429      4.373689e-40
478      2.927314e-38
             ...
85154    4.836071e-01
85229    4.841624e-01
85256    4.843636e-01
85280    4.845820e-01
85289    4.846151e-01
Name: Qvalue, Length: 3046, dtype: float64

In [89]:
filtered_qvalue=filtered_df3[filtered_df3["Qvalue"] < 0.05]
num_qvalue=len(filtered_qvalue)
print(f"number of qvalues <0.05: {num_qvalue}")

number of qvalues <0.05: 1066

In [ ]:
# diffrentially expressed genes in (Y_AL / Y_DR) are =1066

In [90]:
pwd

'C:\\Users\\91918'

In [91]:
df4=df3

In [92]:
df4

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [93]:
filtered_df4=df4[df4["Comparison (group1/group2)"] == "Y_NR / Y_AL"]
display(filtered_df4)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
4325,Y_NR / Y_AL,P04264,P04264,0.854003,0.854003,7.987198e-12,7.632704e-11,387,NaN,NaN,SWISS-PROT:P04264 Tax_Id=9606 Gene_Symbol=KRT1...,P04264,40,80.750980,1.807510,Y_NR,Y_AL,NaN,NaN,NaN
4913,Y_NR / Y_AL,Q05920,Q05920,0.001992,0.001992,9.723397e-11,8.180000e-10,1353,Q05920,Pc,"Pyruvate carboxylase, mitochondrial",PYC_MOUSE,70,0.138194,1.001382,Y_NR,Y_AL,"cytoplasm,mitochondrion,mitochondrial inner me...","biotin carboxylase activity,pyruvate carboxyla...","pyruvate metabolic process,gluconeogenesis,lip..."
6127,Y_NR / Y_AL,P35527,P35527,0.549248,0.549248,5.270083e-09,3.555242e-08,341,NaN,NaN,SWISS-PROT:P35527 Tax_Id=9606 Gene_Symbol=KRT9...,P35527,26,46.332267,1.463323,Y_NR,Y_AL,NaN,NaN,NaN
6383,Y_NR / Y_AL,P35908,P35908,0.590602,0.590602,1.078397e-08,6.983229e-08,275,NaN,NaN,SWISS-PROT:P35908 Tax_Id=9606 Gene_Symbol=KRT2...,P35908,25,50.587542,1.505875,Y_NR,Y_AL,NaN,NaN,NaN
7835,Y_NR / Y_AL,Q9R0H0,Q9R0H0,-0.336049,0.336049,2.206985e-07,1.164328e-06,984,Q9R0H0,Acox1,Peroxisomal acyl-coenzyme A oxidase 1,ACOX1_MOUSE,48,-20.779192,0.792208,Y_NR,Y_AL,"nucleus,nucleoplasm,nucleolus,cytoplasm,mitoch...","acyl-CoA dehydrogenase activity,acyl-CoA oxida...","very long-chain fatty acid metabolic process,g..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85266,Y_NR / Y_AL,Q76LS9,Q76LS9,-0.282291,0.282291,9.992437e-01,4.844577e-01,49,Q76LS9,Fam63a,Protein FAM63A,FA63A_MOUSE,5,-17.771577,0.822284,Y_NR,Y_AL,extracellular exosome,thiol-dependent ubiquitin-specific protease ac...,protein K48-linked deubiquitination
85281,Y_NR / Y_AL,O88829,O88829,0.111293,0.111293,9.996967e-01,4.845820e-01,18,O88829,St3gal5,"Lactosylceramide alpha-2,3-sialyltransferase",SIAT9_MOUSE,2,8.019554,1.080196,Y_NR,Y_AL,"Golgi membrane,integral component of membrane","lactosylceramide alpha-2,3-sialyltransferase a...","oligosaccharide metabolic process,protein N-li..."
85283,Y_NR / Y_AL,Q3TIV5,Q3TIV5,0.043075,0.043075,9.997123e-01,4.845820e-01,20,Q3TIV5,Zc3h15,Zinc finger CCCH domain-containing protein 15,ZC3HF_MOUSE,2,3.030778,1.030308,Y_NR,Y_AL,"nucleolus,cytosol","RNA binding,cadherin binding,metal ion binding",cytokine-mediated signaling pathway
85287,Y_NR / Y_AL,Q9WUP7,Q9WUP7,0.076906,0.076906,9.997346e-01,4.845820e-01,100,Q9WUP7,Uchl5,Ubiquitin carboxyl-terminal hydrolase isozyme L5,UCHL5_MOUSE,9,5.475341,1.054753,Y_NR,Y_AL,"nucleus,nucleoplasm,cytoplasm,mitochondrion,cy...","RNA binding,thiol-dependent ubiquitin-specific...","DNA repair,DNA recombination,transcription, DN..."
85290,Y_NR / Y_AL,P16294,P16294,-0.095468,0.095468,9.998653e-01,4.846165e-01,30,P16294,F9,Coagulation factor IX,FA9_MOUSE,3,-6.403123,0.935969,Y_NR,Y_AL,"extracellular space,extracellular exosome","endopeptidase activity,serine-type endopeptida...","proteolysis,blood coagulation,zymogen activation"

In [94]:
display(filtered_df4["Qvalue"])

4325     7.632704e-11
4913     8.180000e-10
6127     3.555242e-08
6383     6.983229e-08
7835     1.164328e-06
             ...
85266    4.844577e-01
85281    4.845820e-01
85283    4.845820e-01
85287    4.845820e-01
85290    4.846165e-01
Name: Qvalue, Length: 3047, dtype: float64

In [96]:
filtered_qvalue=filtered_df4[filtered_df4["Qvalue"] < 0.05]
num_qvalue=len(filtered_qvalue)
print(f"number of qvalues <0.05: {num_qvalue}")

number of qvalues <0.05: 248

# differentially expressed genes in ( Y_NR/Y_AL ) are =248

In [1]:
pwd

'C:\\Users\\91918\\rna seq'

In [3]:
import os 
os.chdir("C:/Users//91918")

In [4]:
pwd

'C:\\Users\\91918'

In [7]:
import pandas as pd
df5=pd.read_excel("liver proteome.xlsx")

In [8]:
df5

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [11]:
filtered_df5=df5[df5["Comparison (group1/group2)"] == "Y_NRDR / Y_AL"]
display(filtered_df5)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
8,Y_NRDR / Y_AL,Q8C196,Q8C196,0.441013,0.441013,9.427715e-189,4.330464e-185,3491,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,35.755700,1.357557,Y_NRDR,Y_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
99,Y_NRDR / Y_AL,Q99LB7,Q99LB7,0.236349,0.236349,6.423189e-72,2.655346e-69,1243,Q99LB7,Sardh,"Sarcosine dehydrogenase, mitochondrial",SARDH_MOUSE,62,17.800752,1.178008,Y_NRDR,Y_AL,"mitochondrion,mitochondrial matrix",sarcosine dehydrogenase activity,"oxidation-reduction process,sarcosine cataboli..."
113,Y_NRDR / Y_AL,O88833,O88833,1.593028,1.593028,7.367441e-69,2.671667e-66,235,O88833,Cyp4a10,Cytochrome P450 4A10,CP4AA_MOUSE,22,201.681844,3.016818,Y_NRDR,Y_AL,"cytoplasm,endoplasmic reticulum membrane,apica...","monooxygenase activity,iron ion binding,arachi...","fatty acid metabolic process,leukotriene B4 ca..."
123,Y_NRDR / Y_AL,Q99K67,Q99K67,0.921387,0.921387,4.236871e-67,1.412518e-64,950,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,89.393485,1.893935,Y_NRDR,Y_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
157,Y_NRDR / Y_AL,P52825,P52825,0.587015,0.587015,1.850490e-61,4.841726e-59,467,P52825,Cpt2,"Carnitine O-palmitoyltransferase 2, mitochondrial",CPT2_MOUSE,31,50.213546,1.502135,Y_NRDR,Y_AL,"nucleoplasm,nucleolus,mitochondrion,mitochondr...",carnitine O-palmitoyltransferase activity,"fatty acid metabolic process,transport"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85264,Y_NRDR / Y_AL,P10711,P10711,-0.085954,0.085954,9.991991e-01,4.844474e-01,84,P10711,Tcea1,Transcription elongation factor A protein 1,TCEA1_MOUSE,8,-5.783867,0.942161,Y_NRDR,Y_AL,"nucleus,nucleoplasm,transcription factor TFIID...","DNA binding,protein binding,zinc ion binding","transcription, DNA-templated,erythrocyte diffe..."
85272,Y_NRDR / Y_AL,Q62087,Q62087,0.009904,0.009904,9.994199e-01,4.845157e-01,179,Q62087,Pon3,Serum paraoxonase/lactonase 3,PON3_MOUSE,12,0.688877,1.006889,Y_NRDR,Y_AL,"extracellular space,intracellular membrane-bou...","aryldialkylphosphatase activity,arylesterase a...","response to toxic substance,phenylacetate cata..."
85276,Y_NRDR / Y_AL,Q8BG05,Q8BG05,-0.062646,0.062646,9.995017e-01,4.845316e-01,468,Q8BG05,Hnrnpa3,Heterogeneous nuclear ribonucleoprotein A3,ROA3_MOUSE,25,-4.249371,0.957506,Y_NRDR,Y_AL,spliceosomal complex,RNA binding,"mRNA processing,RNA splicing"
85284,Y_NRDR / Y_AL,Q9ESD7,Q9ESD7,0.009113,0.009113,9.996780e-01,4.845820e-01,29,Q9ESD7,Dysf,Dysferlin,DYSF_MOUSE,2,0.633664,1.006337,Y_NRDR,Y_AL,"endosome,early endosome,late endosome,microtub...","calcium ion binding,protein binding,phospholip...","plasma membrane repair,vesicle fusion,muscle c..."
85291,Y_NRDR / Y_AL,P27786,P27786,0.043313,0.043313,9.998716e-01,4.846165e-01,312,P27786,Cyp17a1,"Steroid 17-alpha-hydroxylase/17,20 lyase",CP17A_MOUSE,23,3.047774,1.030478,Y_NRDR,Y_AL,"mitochondrion,membrane,axon,neuronal cell body","steroid 17-alpha-monooxygenase activity,iron i...","glucocorticoid biosynthetic process,steroid me..."

In [12]:
display(filtered_df5["Qvalue"])

8        4.330464e-185
99        2.655346e-69
113       2.671667e-66
123       1.412518e-64
157       4.841726e-59
             ...
85264     4.844474e-01
85272     4.845157e-01
85276     4.845316e-01
85284     4.845820e-01
85291     4.846165e-01
Name: Qvalue, Length: 3040, dtype: float64

In [15]:
filtered_qvalue=filtered_df5[filtered_df5["Qvalue"] < 0.05]
num_qvalue=len(filtered_qvalue)
print(f"number of qvalues <0.05: {num_qvalue}")

number of qvalues <0.05: 1304