In [5]:
pwd

'C:\\Users\\91918\\rna seq'

In [6]:
import os
os.chdir("C:\\Users\\91918")

In [57]:
import pandas as pd
df=pd.read_excel("resLFC_Y_B6J_4w_AL_vs_NRDR.xlsx")

In [58]:
df

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,gene,log2FoldChange.1
0,Xkr4,1.375127,-0.020519,0.289752,0.683132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Xkr4,-0.020519
1,Gm7341,1.311742,0.056132,0.293330,0.396530,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gm7341,0.056132
2,Sox17,31.231318,0.024077,0.205507,0.871209,0.946150,NaN,NaN,NaN,NaN,NaN,NaN,Sox17,0.024077
3,Gm7357,5.921844,0.003447,0.267812,0.976182,0.989806,NaN,NaN,NaN,NaN,NaN,NaN,Gm7357,0.003447
4,Gm6085,50.962861,0.281661,0.220775,0.086261,0.290996,NaN,NaN,NaN,NaN,NaN,NaN,Gm6085,0.281661
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22873,AC125149.1,5.412648,-0.451383,0.649777,0.029091,0.144153,NaN,NaN,NaN,NaN,NaN,NaN,AC125149.1,-0.451383
22874,AC168977.2,2.975387,-0.017434,0.277389,0.848031,0.937633,NaN,NaN,NaN,NaN,NaN,NaN,AC168977.2,-0.017434
22875,AC168977.1,1.426839,-0.122484,0.324438,0.065331,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AC168977.1,-0.122484
22876,AC149090.1,584.916210,-0.219303,0.151814,0.093259,0.304548,NaN,NaN,NaN,NaN,NaN,NaN,AC149090.1,-0.219303
22877,CAAA01147332.1,469.139410,0.042226,0.141278,0.736688,0.887257,NaN,NaN,NaN,NaN,NaN,NaN,CAAA01147332.1,0.042226

In [26]:
#df.columns

In [27]:
#display(all_padj_values)

In [59]:
padj_filtered = df[df["padj"] < 0.05]
display(padj_filtered)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,gene,log2FoldChange.1
13,Rb1cc1,1574.084970,0.380661,0.114559,3.351949e-04,5.155158e-03,NaN,NaN,NaN,NaN,NaN,NaN,Rb1cc1,0.380661
21,Gm9826,23888.126191,0.626043,0.114376,7.795358e-09,5.547649e-07,NaN,NaN,NaN,NaN,NaN,NaN,Gm9826,0.626043
24,Gm16284,8.632604,-1.910256,0.684834,2.476734e-04,4.051424e-03,NaN,NaN,NaN,NaN,NaN,NaN,Gm16284,-1.910256
56,Tram1,4916.542042,-0.332693,0.131787,5.036685e-03,4.170782e-02,NaN,NaN,NaN,NaN,NaN,NaN,Tram1,-0.332693
81,Jph1,55.481709,1.405542,0.301990,2.161342e-07,1.006851e-05,NaN,NaN,NaN,NaN,NaN,NaN,Jph1,1.405542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22848,Rab11fip2,386.419585,0.853326,0.164901,2.500384e-08,1.526025e-06,NaN,NaN,NaN,NaN,NaN,NaN,Rab11fip2,0.853326
22852,Nanos1,7.645563,2.437464,0.839880,1.622293e-04,2.882931e-03,NaN,NaN,NaN,NaN,NaN,NaN,Nanos1,2.437464
22854,Dennd10,828.927228,-0.466743,0.188369,3.111841e-03,2.889503e-02,NaN,NaN,NaN,NaN,NaN,NaN,Dennd10,-0.466743
22857,Grk5,285.166580,-1.767624,0.199352,4.717929e-20,2.527499e-17,NaN,NaN,NaN,NaN,NaN,NaN,Grk5,-1.767624
22860,Gm5521,328.246277,-0.656727,0.184080,5.143313e-05,1.118308e-03,NaN,NaN,NaN,NaN,NaN,NaN,Gm5521,-0.656727

In [60]:
de_genes = df[df["padj"] < 0.05]  # storing the padj coulumn values information which are less then 0.05 in a varible called de_genes
display(de_genes)

,Unnamed: 0,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,gene,log2FoldChange.1
13,Rb1cc1,1574.084970,0.380661,0.114559,3.351949e-04,5.155158e-03,NaN,NaN,NaN,NaN,NaN,NaN,Rb1cc1,0.380661
21,Gm9826,23888.126191,0.626043,0.114376,7.795358e-09,5.547649e-07,NaN,NaN,NaN,NaN,NaN,NaN,Gm9826,0.626043
24,Gm16284,8.632604,-1.910256,0.684834,2.476734e-04,4.051424e-03,NaN,NaN,NaN,NaN,NaN,NaN,Gm16284,-1.910256
56,Tram1,4916.542042,-0.332693,0.131787,5.036685e-03,4.170782e-02,NaN,NaN,NaN,NaN,NaN,NaN,Tram1,-0.332693
81,Jph1,55.481709,1.405542,0.301990,2.161342e-07,1.006851e-05,NaN,NaN,NaN,NaN,NaN,NaN,Jph1,1.405542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22848,Rab11fip2,386.419585,0.853326,0.164901,2.500384e-08,1.526025e-06,NaN,NaN,NaN,NaN,NaN,NaN,Rab11fip2,0.853326
22852,Nanos1,7.645563,2.437464,0.839880,1.622293e-04,2.882931e-03,NaN,NaN,NaN,NaN,NaN,NaN,Nanos1,2.437464
22854,Dennd10,828.927228,-0.466743,0.188369,3.111841e-03,2.889503e-02,NaN,NaN,NaN,NaN,NaN,NaN,Dennd10,-0.466743
22857,Grk5,285.166580,-1.767624,0.199352,4.717929e-20,2.527499e-17,NaN,NaN,NaN,NaN,NaN,NaN,Grk5,-1.767624
22860,Gm5521,328.246277,-0.656727,0.184080,5.143313e-05,1.118308e-03,NaN,NaN,NaN,NaN,NaN,NaN,Gm5521,-0.656727

In [61]:
gene_list = de_genes["gene"].tolist()

In [68]:
output_file = "de_Genes_Y_B6J_4w_AL_vs_NRDR.xlsx"
de_genes.to_excel(output_file, index=False, engine='openpyxl')

In [69]:
print(f"Total de genes (padj < 0.05): {len(gene_list)}")

Total de genes (padj < 0.05): 2482

In [70]:

# Filter for differentially expressed genes (padj ≤ 0.05)
df_filtered = df[df["padj"] <= 0.05]

# Extract gene names and their log2FoldChange values as a list
degs_list = df_filtered[["gene", "log2FoldChange"]].values.tolist()

# Save to Excel
df_filtered.to_excel("Filtered_DEGs.xlsx", index=False, engine="openpyxl")

# Display first few results
#display(df_filtered.head())
#display(f"Total DEGs (padj ≤ 0.05): {len(df_filtered)}")