In [1]:
pwd

'C:\\Users\\91918\\rna seq'

In [2]:
import os
os.chdir("C://Users//91918")

In [3]:
pwd

'C:\\Users\\91918'

In [4]:
import pandas as pd
df=pd.read_excel("liver proteome2.xlsx")

In [5]:
df

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q5SSH7,Q5SSH7,-0.043644,0.043644,2.219905e-01,1.859767e-01,92,Q5SSH7,Zzef1,Zinc finger ZZ-type and EF-hand domain-contain...,ZZEF1_MOUSE,7,-2.979859,0.970201,O_DR,O_AL,cellular_component,"molecular_function,calcium ion binding,zinc io...",biological_process

In [6]:
filtered_df= df[df["Comparison (group1/group2)"] == "O_DR / O_AL"]
display(filtered_df)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
9,O_DR / O_AL,Q9CW42,Q9CW42,-0.313504,0.313504,2.039394e-06,9.053752e-06,211,Q9CW42,Marc1,Mitochondrial amidoxime-reducing component 1,MARC1_MOUSE,14,-19.531510,0.804685,O_DR,O_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
18,O_DR / O_AL,Q922Q1,Q922Q1,-0.616419,0.616419,7.330797e-15,9.798097e-14,383,Q922Q1,Marc2,Mitochondrial amidoxime reducing component 2,MARC2_MOUSE,18,-34.771205,0.652288,O_DR,O_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
25,O_DR / O_AL,P42208,P42208,-0.069442,0.069442,4.918610e-05,1.636868e-04,206,P42208,Sept2,Septin-2,SEPT2_MOUSE,13,-4.699331,0.953007,O_DR,O_AL,"condensed chromosome kinetochore,nucleus,nucle...","GTPase activity,protein binding,GTP binding,en...","cytokinesis,regulation of L-glutamate transpor..."
29,O_DR / O_AL,O55131,O55131,-0.339668,0.339668,8.053148e-03,1.400076e-02,254,O55131,Sept7,Septin-7,SEPT7_MOUSE,15,-20.977679,0.790223,O_DR,O_AL,"condensed chromosome kinetochore,stress fiber,...","protein binding,GTP binding,identical protein ...","mitotic cytokinesis,spermatogenesis,regulation..."
47,O_DR / O_AL,Q8CHH9,Q8CHH9,0.230365,0.230365,6.200201e-01,3.667267e-01,19,Q8CHH9,Sept8,Septin-8,SEPT8_MOUSE,2,17.313140,1.173131,O_DR,O_AL,"cytoplasm,cytoskeleton,myelin sheath","molecular_function,GTP binding",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85201,O_DR / O_AL,Q80W54,Q80W54,-0.445789,0.445789,1.153215e-03,2.677556e-03,138,Q80W54,Zmpste24,CAAX prenyl protease 1 homolog,FACE1_MOUSE,8,-26.581714,0.734183,O_DR,O_AL,"nuclear inner membrane,membrane,integral compo...","metalloendopeptidase activity,metal ion binding","nuclear envelope organization,prenylated prote..."
85214,O_DR / O_AL,O88291,O88291,-0.113556,0.113556,4.407227e-01,2.947277e-01,52,O88291,Znf326,DBIRD complex subunit ZNF326,ZN326_MOUSE,4,-7.569296,0.924307,O_DR,O_AL,"nucleus,nucleoplasm,nuclear matrix,intracellul...","RNA polymerase II core binding,DNA binding,RNA...","transcription, DNA-templated,mRNA processing,R..."
85220,O_DR / O_AL,Q62384,Q62384,-0.151091,0.151091,2.406114e-01,1.966174e-01,39,Q62384,Zpr1,Zinc finger protein ZPR1,ZPR1_MOUSE,3,-9.943061,0.900569,O_DR,O_AL,"nucleus,nucleoplasm,nucleolus,cytoplasm,Cajal ...","protein binding,zinc ion binding,receptor tyro...","microtubule cytoskeleton organization,inner ce..."
85274,O_DR / O_AL,Q62523,Q62523,0.101964,0.101964,5.226048e-01,3.291840e-01,52,Q62523,Zyx,Zyxin,ZYX_MOUSE,4,7.323362,1.073234,O_DR,O_AL,"stress fiber,nucleus,cytosol,cell-cell adheren...","RNA binding,protein binding,metal ion binding","cell-matrix adhesion,transforming growth facto..."
85297,O_DR / O_AL,Q5SSH7,Q5SSH7,-0.043644,0.043644,2.219905e-01,1.859767e-01,92,Q5SSH7,Zzef1,Zinc finger ZZ-type and EF-hand domain-contain...,ZZEF1_MOUSE,7,-2.979859,0.970201,O_DR,O_AL,cellular_component,"molecular_function,calcium ion binding,zinc io...",biological_process

In [13]:
# drop_duplicates(subset="Genes") keeps only the first occurrence of each unique gene (along with its Q-value).

unique_genes = filtered_df[["Genes", "Qvalue","AVG Log2 Ratio"]].dropna().drop_duplicates(subset="Genes")
print(unique_genes)

          Genes        Qvalue  AVG Log2 Ratio
9         Marc1  9.053752e-06       -0.313504
18        Marc2  9.798097e-14       -0.616419
25        Sept2  1.636868e-04       -0.069442
29        Sept7  1.400076e-02       -0.339668
47        Sept8  3.667267e-01        0.230365
...         ...           ...             ...
85201  Zmpste24  2.677556e-03       -0.445789
85214    Znf326  2.947277e-01       -0.113556
85220      Zpr1  1.966174e-01       -0.151091
85274       Zyx  3.291840e-01        0.101964
85297     Zzef1  1.859767e-01       -0.043644

[2999 rows x 3 columns]

In [14]:
# Save to Excel 
unique_genes.to_excel("unique_genes.xlsx", index=False)

In [16]:
num_unique_genes=len(unique_genes)
print(num_unique_genes)

2999

In [58]:
#unique_genes_list = list(unique_genes)
#display(unique_genes_list)

In [50]:
import os
os.chdir("C://Users//91918")

In [51]:
pwd

'C:\\Users\\91918'

In [21]:
import pandas as pd
df1=pd.read_excel("liver proteome4.xlsx")

In [22]:
df1

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [23]:
filtered_df1= df1[df1["Comparison (group1/group2)"] == "O_NRDR / O_AL"]
display(filtered_df1)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
5,O_NRDR / O_AL,Q9CW42,Q9CW42,-0.542484,0.542484,8.321134e-05,2.626523e-04,218,Q9CW42,Marc1,Mitochondrial amidoxime-reducing component 1,MARC1_MOUSE,14,-31.341242,0.686588,O_NRDR,O_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
12,O_NRDR / O_AL,Q922Q1,Q922Q1,-0.681360,0.681360,4.524032e-15,6.156139e-14,386,Q922Q1,Marc2,Mitochondrial amidoxime reducing component 2,MARC2_MOUSE,18,-37.642270,0.623577,O_NRDR,O_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
30,O_NRDR / O_AL,P42208,P42208,-0.058412,0.058412,1.058768e-05,4.078787e-05,208,P42208,Sept2,Septin-2,SEPT2_MOUSE,13,-3.967939,0.960321,O_NRDR,O_AL,"condensed chromosome kinetochore,nucleus,nucle...","GTPase activity,protein binding,GTP binding,en...","cytokinesis,regulation of L-glutamate transpor..."
38,O_NRDR / O_AL,O55131,O55131,-0.366569,0.366569,8.204662e-03,1.421545e-02,258,O55131,Sept7,Septin-7,SEPT7_MOUSE,15,-22.437517,0.775625,O_NRDR,O_AL,"condensed chromosome kinetochore,stress fiber,...","protein binding,GTP binding,identical protein ...","mitotic cytokinesis,spermatogenesis,regulation..."
40,O_NRDR / O_AL,Q8CHH9,Q8CHH9,-0.231441,0.231441,2.013988e-01,1.734185e-01,23,Q8CHH9,Sept8,Septin-8,SEPT8_MOUSE,2,-14.821643,0.851784,O_NRDR,O_AL,"cytoplasm,cytoskeleton,myelin sheath","molecular_function,GTP binding",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85084,O_NRDR / O_AL,Q80W54,Q80W54,-0.039370,0.039370,2.683553e-01,2.117698e-01,139,Q80W54,Zmpste24,CAAX prenyl protease 1 homolog,FACE1_MOUSE,8,-2.692021,0.973080,O_NRDR,O_AL,"nuclear inner membrane,membrane,integral compo...","metalloendopeptidase activity,metal ion binding","nuclear envelope organization,prenylated prote..."
85150,O_NRDR / O_AL,O88291,O88291,-0.354772,0.354772,2.396430e-03,5.004419e-03,52,O88291,Znf326,DBIRD complex subunit ZNF326,ZN326_MOUSE,4,-21.800705,0.781993,O_NRDR,O_AL,"nucleus,nucleoplasm,nuclear matrix,intracellul...","RNA polymerase II core binding,DNA binding,RNA...","transcription, DNA-templated,mRNA processing,R..."
85238,O_NRDR / O_AL,Q62384,Q62384,-0.355005,0.355005,2.398796e-02,3.425524e-02,39,Q62384,Zpr1,Zinc finger protein ZPR1,ZPR1_MOUSE,3,-21.813292,0.781867,O_NRDR,O_AL,"nucleus,nucleoplasm,nucleolus,cytoplasm,Cajal ...","protein binding,zinc ion binding,receptor tyro...","microtubule cytoskeleton organization,inner ce..."
85258,O_NRDR / O_AL,Q62523,Q62523,-0.056931,0.056931,6.371463e-01,3.729135e-01,52,Q62523,Zyx,Zyxin,ZYX_MOUSE,4,-3.869281,0.961307,O_NRDR,O_AL,"stress fiber,nucleus,cytosol,cell-cell adheren...","RNA binding,protein binding,metal ion binding","cell-matrix adhesion,transforming growth facto..."
85288,O_NRDR / O_AL,Q5SSH7,Q5SSH7,0.173518,0.173518,1.542225e-01,1.430909e-01,91,Q5SSH7,Zzef1,Zinc finger ZZ-type and EF-hand domain-contain...,ZZEF1_MOUSE,7,12.780558,1.127806,O_NRDR,O_AL,cellular_component,"molecular_function,calcium ion binding,zinc io...",biological_process

In [24]:
unique_genes1 = filtered_df1[["Genes","Qvalue","AVG Log2 Ratio"]].dropna().drop_duplicates(subset="Genes")
print(unique_genes1)

          Genes        Qvalue  AVG Log2 Ratio
5         Marc1  2.626523e-04       -0.542484
12        Marc2  6.156139e-14       -0.681360
30        Sept2  4.078787e-05       -0.058412
38        Sept7  1.421545e-02       -0.366569
40        Sept8  1.734185e-01       -0.231441
...         ...           ...             ...
85084  Zmpste24  2.117698e-01       -0.039370
85150    Znf326  5.004419e-03       -0.354772
85238      Zpr1  3.425524e-02       -0.355005
85258       Zyx  3.729135e-01       -0.056931
85288     Zzef1  1.430909e-01        0.173518

[2997 rows x 3 columns]

In [25]:
num_unique_genes1=len(unique_genes1)
print(num_unique_genes1)

2997

In [26]:
# Save to Excel 
unique_genes1.to_excel("unique_genes.xlsx", index=False)

In [88]:
pwd

'C:\\Users\\91918'

In [27]:
df2=pd.read_excel("liver proteome5.xlsx")

In [28]:
df2

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [29]:
filtered_df2= df2[df2["Comparison (group1/group2)"] == "Y_DR / Y_AL"]
display(filtered_df2)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
41,Y_DR / Y_AL,Q9CW42,Q9CW42,-0.087572,0.087572,0.644624,0.375604,168,Q9CW42,Marc1,Mitochondrial amidoxime-reducing component 1,MARC1_MOUSE,14,-5.889461,0.941105,Y_DR,Y_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
229,Y_DR / Y_AL,Q922Q1,Q922Q1,0.012412,0.012412,0.977546,0.479094,299,Q922Q1,Marc2,Mitochondrial amidoxime reducing component 2,MARC2_MOUSE,18,0.864058,1.008641,Y_DR,Y_AL,"mitochondrion,mitochondrial outer membrane,mit...","nitrate reductase activity,molybdenum ion bind...","nitrate metabolic process,oxidation-reduction ..."
328,Y_DR / Y_AL,P42208,P42208,-0.068650,0.068650,0.000459,0.001195,159,P42208,Sept2,Septin-2,SEPT2_MOUSE,13,-4.646985,0.953530,Y_DR,Y_AL,"condensed chromosome kinetochore,nucleus,nucle...","GTPase activity,protein binding,GTP binding,en...","cytokinesis,regulation of L-glutamate transpor..."
429,Y_DR / Y_AL,O55131,O55131,-0.020751,0.020751,0.006457,0.011641,197,O55131,Sept7,Septin-7,SEPT7_MOUSE,15,-1.428024,0.985720,Y_DR,Y_AL,"condensed chromosome kinetochore,stress fiber,...","protein binding,GTP binding,identical protein ...","mitotic cytokinesis,spermatogenesis,regulation..."
478,Y_DR / Y_AL,Q8CHH9,Q8CHH9,-0.185371,0.185371,0.251903,0.203035,16,Q8CHH9,Sept8,Septin-8,SEPT8_MOUSE,2,-12.057739,0.879423,Y_DR,Y_AL,"cytoplasm,cytoskeleton,myelin sheath","molecular_function,GTP binding",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85154,Y_DR / Y_AL,Q80W54,Q80W54,-0.215924,0.215924,0.020612,0.030292,107,Q80W54,Zmpste24,CAAX prenyl protease 1 homolog,FACE1_MOUSE,8,-13.900518,0.860995,Y_DR,Y_AL,"nuclear inner membrane,membrane,integral compo...","metalloendopeptidase activity,metal ion binding","nuclear envelope organization,prenylated prote..."
85229,Y_DR / Y_AL,O88291,O88291,-0.093958,0.093958,0.242996,0.198026,40,O88291,Znf326,DBIRD complex subunit ZNF326,ZN326_MOUSE,4,-6.305146,0.936949,Y_DR,Y_AL,"nucleus,nucleoplasm,nuclear matrix,intracellul...","RNA polymerase II core binding,DNA binding,RNA...","transcription, DNA-templated,mRNA processing,R..."
85256,Y_DR / Y_AL,Q62384,Q62384,-0.428086,0.428086,0.001516,0.003388,29,Q62384,Zpr1,Zinc finger protein ZPR1,ZPR1_MOUSE,3,-25.675266,0.743247,Y_DR,Y_AL,"nucleus,nucleoplasm,nucleolus,cytoplasm,Cajal ...","protein binding,zinc ion binding,receptor tyro...","microtubule cytoskeleton organization,inner ce..."
85280,Y_DR / Y_AL,Q62523,Q62523,-0.073787,0.073787,0.622573,0.367680,40,Q62523,Zyx,Zyxin,ZYX_MOUSE,4,-4.985948,0.950141,Y_DR,Y_AL,"stress fiber,nucleus,cytosol,cell-cell adheren...","RNA binding,protein binding,metal ion binding","cell-matrix adhesion,transforming growth facto..."
85289,Y_DR / Y_AL,Q5SSH7,Q5SSH7,-0.254043,0.254043,0.602112,0.360164,70,Q5SSH7,Zzef1,Zinc finger ZZ-type and EF-hand domain-contain...,ZZEF1_MOUSE,7,-16.145700,0.838543,Y_DR,Y_AL,cellular_component,"molecular_function,calcium ion binding,zinc io...",biological_process

In [33]:
unique_genes2 = filtered_df2[["Genes","Qvalue","AVG Log2 Ratio"]].dropna().drop_duplicates(subset="Genes")
print(unique_genes2)

          Genes    Qvalue  AVG Log2 Ratio
41        Marc1  0.375604       -0.087572
229       Marc2  0.479094        0.012412
328       Sept2  0.001195       -0.068650
429       Sept7  0.011641       -0.020751
478       Sept8  0.203035       -0.185371
...         ...       ...             ...
85154  Zmpste24  0.030292       -0.215924
85229    Znf326  0.198026       -0.093958
85256      Zpr1  0.003388       -0.428086
85280       Zyx  0.367680       -0.073787
85289     Zzef1  0.360164       -0.254043

[2996 rows x 3 columns]

In [34]:
num_unique_genes2=len(unique_genes2)
print(num_unique_genes2)

2996

In [35]:
unique_genes2.to_excel("unique_genes.xlsx", index=False)

In [46]:
df3=pd.read_excel("liver proteome7.1.xlsx")

In [47]:
df3

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [48]:
filtered_df3= df3[df3["Comparison (group1/group2)"] == "Y_NRDR / Y_AL"]
display(filtered_df3)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
8,Y_NRDR / Y_AL,Q8C196,Q8C196,0.441013,0.441013,9.427715e-189,4.330464e-185,3491,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,35.755700,1.357557,Y_NRDR,Y_AL,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
99,Y_NRDR / Y_AL,Q99LB7,Q99LB7,0.236349,0.236349,6.423189e-72,2.655346e-69,1243,Q99LB7,Sardh,"Sarcosine dehydrogenase, mitochondrial",SARDH_MOUSE,62,17.800752,1.178008,Y_NRDR,Y_AL,"mitochondrion,mitochondrial matrix",sarcosine dehydrogenase activity,"oxidation-reduction process,sarcosine cataboli..."
113,Y_NRDR / Y_AL,O88833,O88833,1.593028,1.593028,7.367441e-69,2.671667e-66,235,O88833,Cyp4a10,Cytochrome P450 4A10,CP4AA_MOUSE,22,201.681844,3.016818,Y_NRDR,Y_AL,"cytoplasm,endoplasmic reticulum membrane,apica...","monooxygenase activity,iron ion binding,arachi...","fatty acid metabolic process,leukotriene B4 ca..."
123,Y_NRDR / Y_AL,Q99K67,Q99K67,0.921387,0.921387,4.236871e-67,1.412518e-64,950,Q99K67,Aass,"Alpha-aminoadipic semialdehyde synthase, mitoc...",AASS_MOUSE,54,89.393485,1.893935,Y_NRDR,Y_AL,"mitochondrion,intracellular membrane-bounded o...","saccharopine dehydrogenase (NADP+, L-lysine-fo...",generation of precursor metabolites and energy...
157,Y_NRDR / Y_AL,P52825,P52825,0.587015,0.587015,1.850490e-61,4.841726e-59,467,P52825,Cpt2,"Carnitine O-palmitoyltransferase 2, mitochondrial",CPT2_MOUSE,31,50.213546,1.502135,Y_NRDR,Y_AL,"nucleoplasm,nucleolus,mitochondrion,mitochondr...",carnitine O-palmitoyltransferase activity,"fatty acid metabolic process,transport"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85264,Y_NRDR / Y_AL,P10711,P10711,-0.085954,0.085954,9.991991e-01,4.844474e-01,84,P10711,Tcea1,Transcription elongation factor A protein 1,TCEA1_MOUSE,8,-5.783867,0.942161,Y_NRDR,Y_AL,"nucleus,nucleoplasm,transcription factor TFIID...","DNA binding,protein binding,zinc ion binding","transcription, DNA-templated,erythrocyte diffe..."
85272,Y_NRDR / Y_AL,Q62087,Q62087,0.009904,0.009904,9.994199e-01,4.845157e-01,179,Q62087,Pon3,Serum paraoxonase/lactonase 3,PON3_MOUSE,12,0.688877,1.006889,Y_NRDR,Y_AL,"extracellular space,intracellular membrane-bou...","aryldialkylphosphatase activity,arylesterase a...","response to toxic substance,phenylacetate cata..."
85276,Y_NRDR / Y_AL,Q8BG05,Q8BG05,-0.062646,0.062646,9.995017e-01,4.845316e-01,468,Q8BG05,Hnrnpa3,Heterogeneous nuclear ribonucleoprotein A3,ROA3_MOUSE,25,-4.249371,0.957506,Y_NRDR,Y_AL,spliceosomal complex,RNA binding,"mRNA processing,RNA splicing"
85284,Y_NRDR / Y_AL,Q9ESD7,Q9ESD7,0.009113,0.009113,9.996780e-01,4.845820e-01,29,Q9ESD7,Dysf,Dysferlin,DYSF_MOUSE,2,0.633664,1.006337,Y_NRDR,Y_AL,"endosome,early endosome,late endosome,microtub...","calcium ion binding,protein binding,phospholip...","plasma membrane repair,vesicle fusion,muscle c..."
85291,Y_NRDR / Y_AL,P27786,P27786,0.043313,0.043313,9.998716e-01,4.846165e-01,312,P27786,Cyp17a1,"Steroid 17-alpha-hydroxylase/17,20 lyase",CP17A_MOUSE,23,3.047774,1.030478,Y_NRDR,Y_AL,"mitochondrion,membrane,axon,neuronal cell body","steroid 17-alpha-monooxygenase activity,iron i...","glucocorticoid biosynthetic process,steroid me..."

In [49]:
unique_genes3 = filtered_df3[["Genes","Qvalue","AVG Log2 Ratio"]].dropna().drop_duplicates(subset="Genes")
print(unique_genes3)

         Genes         Qvalue  AVG Log2 Ratio
8         Cps1  4.330464e-185        0.441013
99       Sardh   2.655346e-69        0.236349
113    Cyp4a10   2.671667e-66        1.593028
123       Aass   1.412518e-64        0.921387
157       Cpt2   4.841726e-59        0.587015
...        ...            ...             ...
85264    Tcea1   4.844474e-01       -0.085954
85272     Pon3   4.845157e-01        0.009904
85276  Hnrnpa3   4.845316e-01       -0.062646
85284     Dysf   4.845820e-01        0.009113
85291  Cyp17a1   4.846165e-01        0.043313

[2991 rows x 3 columns]

In [50]:
num_unique_genes3=len(unique_genes3)
print(num_unique_genes3)

2991

In [51]:
unique_genes3.to_excel("unique_genes.xlsx", index=False)

In [87]:
df5=pd.read_excel("liver proteome7.1.xlsx")

In [88]:
df5

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
0,O_AL / Y_NRDR,Q8C196,Q8C196,-0.809178,0.809178,0.000000e+00,0.000000e+00,3847,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-42.929303,0.570707,O_AL,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
1,O_NR / Y_NRDR,Q8C196,Q8C196,-0.913840,0.913840,0.000000e+00,0.000000e+00,3846,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-46.922960,0.530770,O_NR,Y_NRDR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
2,O_NR / Y_DR,Q8C196,Q8C196,-0.710514,0.710514,3.164386e-307,4.360523e-303,3842,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-38.889773,0.611102,O_NR,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
3,O_AL / Y_DR,Q8C196,Q8C196,-0.605852,0.605852,3.151609e-293,3.257188e-289,3843,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,-34.291678,0.657083,O_AL,Y_DR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
4,O_NRDR / O_NR,Q8C196,Q8C196,0.615371,0.615371,3.461765e-279,2.862187e-275,4538,Q8C196,Cps1,"Carbamoyl-phosphate synthase [ammonia], mitoch...",CPSM_MOUSE,151,53.195188,1.531952,O_NRDR,O_NR,"nucleolus,mitochondrion,mitochondrial inner me...",carbamoyl-phosphate synthase (ammonia) activit...,"urea cycle,'de novo' pyrimidine nucleobase bio..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85293,O_NR / Y_DR,Q9D710,Q9D710,0.136878,0.136878,9.998646e-01,4.846165e-01,44,Q9D710,Tmx2,Thioredoxin-related transmembrane protein 2,TMX2_MOUSE,4,9.952353,1.099524,O_NR,Y_DR,"cellular_component,cell,integral component of ...",molecular_function,"biological_process,cell redox homeostasis"
85294,O_AL / Y_AL,Q9QUR7,Q9QUR7,0.070849,0.070849,9.999124e-01,4.846284e-01,43,Q9QUR7,Pin1,Peptidyl-prolyl cis-trans isomerase NIMA-inter...,PIN1_MOUSE,4,5.033474,1.050335,O_AL,Y_AL,"nucleus,nucleoplasm,cytosol,nuclear speck,midbody","peptidyl-prolyl cis-trans isomerase activity,m...","protein peptidyl-prolyl isomerization,positive..."
85295,O_NRDR / O_NR,P54731,P54731,-0.067533,0.067533,9.999762e-01,4.846447e-01,52,P54731,Faf1,FAS-associated factor 1,FAF1_MOUSE,4,-4.573161,0.954268,O_NRDR,O_NR,"nucleus,nuclear envelope,cytoplasm,cytosol,VCP...","protein binding,protein kinase binding,protein...","apoptotic process,cytoplasmic sequestering of ..."
85296,Y_NRDR / Y_DR,Q99K48,Q99K48,-0.041905,0.041905,9.999812e-01,4.846447e-01,213,Q99K48,Nono,Non-POU domain-containing octamer-binding protein,NONO_MOUSE,18,-2.862850,0.971372,Y_NRDR,Y_DR,"nucleus,nucleoplasm,nucleolus,membrane,nuclear...",RNA polymerase II distal enhancer sequence-spe...,"mRNA splicing, via spliceosome,DNA repair,DNA ..."
85297,O_DR / O_AL,Q9Z0N1,Q9Z0N1,0.032731,0.032731,9.999621e-01,4.846447e-01,86,Q9Z0N1,Eif2s3x,Eukaryotic translation initiation factor 2 sub...,IF2G_MOUSE,15,2.294686,1.022947,O_DR,O_AL,"cytoplasm,eukaryotic translation initiation fa...","translation initiation factor activity,GTPase ...",translational initiation

In [91]:
filtered_df5= df5[df5["Comparison (group1/group2)"] == "O_NR / O_AL"]
display(filtered_df5)

,Comparison (group1/group2),Group,ProteinGroups,AVG Log2 Ratio,Absolute AVG Log2 Ratio,Pvalue,Qvalue,# of Ratios,UniProtIds,Genes,ProteinDescriptions,ProteinNames,# Unique Total Peptides,% Change,Ratio,Condition Numerator,Condition Denominator,GO Cellular Component,GO Molecular Function,GO Biological Process
3678,O_NR / O_AL,Q99PL5,Q99PL5,-0.123758,0.123758,3.434753e-13,3.859546e-12,1612,Q99PL5,Rrbp1,Ribosome-binding protein 1,RRBP1_MOUSE,85,-8.220595,0.917794,O_NR,O_AL,"ribosome,integral component of endoplasmic ret...","receptor activity,protein binding","translation,signal transduction,protein transport"
3833,O_NR / O_AL,P97501,P97501,-0.373383,0.373383,7.524971e-13,8.113779e-12,530,P97501,Fmo3,Dimethylaniline monooxygenase [N-oxide-forming] 3,FMO3_MOUSE,26,-22.803003,0.771970,O_NR,O_AL,"endoplasmic reticulum membrane,integral compon...","monooxygenase activity,N,N-dimethylaniline mon...",oxidation-reduction process
3919,O_NR / O_AL,P43883,P43883,0.524577,0.524577,1.167484e-12,1.231219e-11,286,P43883,Plin2,Perilipin-2,PLIN2_MOUSE,17,43.851128,1.438511,O_NR,O_AL,"nucleus,cytoplasm,lipid particle,cytosol,plasm...",protein binding,"response to organic cyclic compound,long-chain..."
4995,O_NR / O_AL,P25688,P25688,-0.308591,0.308591,1.291291e-10,1.068494e-09,886,P25688,Uox,Uricase,URIC_MOUSE,30,-19.257009,0.807430,O_NR,O_AL,"mitochondrion,peroxisome",urate oxidase activity,"purine nucleobase metabolic process,urate cata..."
5092,O_NR / O_AL,Q8CC88,Q8CC88,0.152147,0.152147,1.842818e-10,1.495820e-09,1010,Q8CC88,Vwa8,von Willebrand factor A domain-containing prot...,VWA8_MOUSE,72,11.122172,1.111222,O_NR,O_AL,"extracellular region,mitochondrion","molecular_function,ATP binding,ATPase activity",biological_process
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85130,O_NR / O_AL,Q8C0D5,Q8C0D5,-0.093973,0.093973,9.956963e-01,4.835146e-01,83,Q8C0D5,Eftud1,Elongation factor Tu GTP-binding domain-contai...,ETUD1_MOUSE,8,-6.306077,0.936939,O_NR,O_AL,NaN,"translation elongation factor activity,GTPase ...","translational elongation,mature ribosome assem..."
85135,O_NR / O_AL,O08573,O08573,-0.080574,0.080574,9.958675e-01,4.835625e-01,203,O08573,Lgals9,Galectin-9,LEG9_MOUSE,13,-5.431855,0.945681,O_NR,O_AL,"extracellular region,intracellular,nucleus,cyt...","receptor binding,protein binding,galactoside b...","positive regulation of cytokine production,imm..."
85140,O_NR / O_AL,Q61112,Q61112,0.041969,0.041969,9.959198e-01,4.835664e-01,24,Q61112,Sdf4,45 kDa calcium-binding protein,CAB45_MOUSE,2,2.951821,1.029518,O_NR,O_AL,"late endosome,Golgi apparatus,Golgi lumen,memb...",calcium ion binding,"UV protection,cerebellum development,fat cell ..."
85183,O_NR / O_AL,Q6P542,Q6P542,0.231689,0.231689,9.969824e-01,4.838266e-01,180,Q6P542,Abcf1,ATP-binding cassette sub-family F member 1,ABCF1_MOUSE,15,17.420850,1.174208,O_NR,O_AL,"nuclear envelope,nucleoplasm,cytoplasm,cytosol...","RNA binding,ATP binding,translation activator ...","translational initiation,positive regulation o..."
85216,O_NR / O_AL,Q8R1Q9,Q8R1Q9,0.073797,0.073797,9.978415e-01,4.840683e-01,48,Q8R1Q9,Rbks,Ribokinase,RBSK_MOUSE,4,5.248339,1.052483,O_NR,O_AL,"nucleus,cytoplasm,extracellular exosome","ribokinase activity,ATP binding,carbohydrate k...","D-ribose catabolic process,carbohydrate phosph..."

In [92]:
unique_genes5 = filtered_df5[["Genes","Qvalue","AVG Log2 Ratio"]].dropna().drop_duplicates(subset="Genes")
print(unique_genes5)

        Genes        Qvalue  AVG Log2 Ratio
3678    Rrbp1  3.859546e-12       -0.123758
3833     Fmo3  8.113779e-12       -0.373383
3919    Plin2  1.231219e-11        0.524577
4995      Uox  1.068494e-09       -0.308591
5092     Vwa8  1.495820e-09        0.152147
...       ...           ...             ...
85130  Eftud1  4.835146e-01       -0.093973
85135  Lgals9  4.835625e-01       -0.080574
85140    Sdf4  4.835664e-01        0.041969
85183   Abcf1  4.838266e-01        0.231689
85216    Rbks  4.840683e-01        0.073797

[2999 rows x 3 columns]

In [93]:
num_unique_genes5=len(unique_genes5)
print(num_unique_genes5)

2999

In [94]:
unique_genes5.to_excel("unique_genes.xlsx", index=False)

In [95]:
df4=pd.read_excel("resLFC_O_B6J_4w_AL_vs_NR.xlsx")

In [96]:
df4

,gene,baseMean,log2FoldChange,lfcSE,pvalue,padj,Unnamed: 6,Unnamed: 7,Unnamed: 8,-log2FC
0,Xkr4,2.449316,2.895589e-07,0.001443,0.783650,0.999926,NaN,NaN,NaN,-2.895589e-07
1,Sox17,24.891324,-6.944587e-07,0.001443,0.765563,0.999926,NaN,NaN,NaN,6.944587e-07
2,Gm7357,5.078738,-9.419395e-07,0.001443,0.572615,0.999926,NaN,NaN,NaN,9.419395e-07
3,Gm6085,42.499403,2.544385e-06,0.001443,0.537142,0.999926,NaN,NaN,NaN,-2.544385e-06
4,Gm6119,5.569959,-8.486273e-07,0.001443,0.577642,0.999926,NaN,NaN,NaN,8.486273e-07
...,...,...,...,...,...,...,...,...,...,...
23623,AC125149.4,0.582299,-2.696822e-07,0.001443,0.466881,0.999926,NaN,NaN,NaN,2.696822e-07
23624,AC168977.2,11.055031,9.581723e-07,0.001443,0.642268,0.999926,NaN,NaN,NaN,-9.581723e-07
23625,AC168977.1,22.016405,2.363822e-06,0.001443,0.116955,0.999926,NaN,NaN,NaN,-2.363822e-06
23626,AC149090.1,610.601180,-2.409320e-06,0.001443,0.643544,0.999926,NaN,NaN,NaN,2.409320e-06
23627,CAAA01147332.1,408.820909,-4.827505e-06,0.001443,0.374228,0.999926,NaN,NaN,NaN,4.827505e-06

In [97]:
unique_genes4 = filtered_df4["gene"].dropna()
print(unique_genes4)

1                 Sox17
2                Gm7357
3                Gm6085
4                Gm6119
5                Gm6123
              ...
23621        AC125149.1
23624        AC168977.2
23625        AC168977.1
23626        AC149090.1
23627    CAAA01147332.1
Name: gene, Length: 17494, dtype: object

In [98]:
num_unique_genes4=len(unique_genes4)
print(num_unique_genes4)

17494